import type { CatalogFood } from './food-catalog';

/**
 * Large add-on catalog for Add Ingredient search.
 * Values are approximate per default portion (qty 1).
 */
export const EXTRA_FOODS: CatalogFood[] = [
  // —— Dairy / milk ——
  { name: 'Whole milk', portion: '1 cup', protein_g: 8, calories_g: 149, estimated_grams: 244, aliases: ['full fat milk', 'full-fat milk', 'whole cows milk', 'full cream milk', 'blue top'] },
  { name: 'Semi-skimmed milk', portion: '1 cup', protein_g: 8.4, calories_g: 120, estimated_grams: 244, aliases: ['semiskimmed milk', 'semi skimmed milk', 'semi skimmed', '2% milk', 'reduced fat milk', 'green top'] },
  { name: 'Skimmed milk', portion: '1 cup', protein_g: 8.3, calories_g: 83, estimated_grams: 245, aliases: ['skim milk', 'fat free milk', '0% milk', 'nonfat milk', 'red top'] },
  { name: '1% milk', portion: '1 cup', protein_g: 8.2, calories_g: 102, estimated_grams: 244, aliases: ['one percent milk', 'low fat milk'] },
  { name: '2% milk', portion: '1 cup', protein_g: 8.1, calories_g: 122, estimated_grams: 244, aliases: ['two percent milk'] },
  { name: 'Lactose-free milk', portion: '1 cup', protein_g: 8, calories_g: 120, estimated_grams: 244, aliases: ['lactose free milk'] },
  { name: 'A2 milk', portion: '1 cup', protein_g: 8, calories_g: 130, estimated_grams: 244 },
  { name: 'Organic milk', portion: '1 cup', protein_g: 8, calories_g: 130, estimated_grams: 244 },
  { name: 'Raw milk', portion: '1 cup', protein_g: 8, calories_g: 150, estimated_grams: 244 },
  { name: 'Goat milk', portion: '1 cup', protein_g: 8.7, calories_g: 168, estimated_grams: 244 },
  { name: 'Sheep milk', portion: '1 cup', protein_g: 8.7, calories_g: 265, estimated_grams: 245 },
  { name: 'Buffalo milk', portion: '1 cup', protein_g: 9, calories_g: 237, estimated_grams: 244 },
  { name: 'Camel milk', portion: '1 cup', protein_g: 7.5, calories_g: 120, estimated_grams: 244 },
  { name: 'Condensed milk', portion: '2 tbsp', protein_g: 2.4, calories_g: 130, estimated_grams: 38 },
  { name: 'Evaporated milk', portion: '2 tbsp', protein_g: 2.5, calories_g: 40, estimated_grams: 30 },
  { name: 'Powdered milk', portion: '2 tbsp', protein_g: 5, calories_g: 80, estimated_grams: 20, aliases: ['milk powder', 'dried milk'] },
  { name: 'Buttermilk', portion: '1 cup', protein_g: 8, calories_g: 98, estimated_grams: 245 },
  {
    name: 'Chocolate milk',
    portion: '1 cup',
    protein_g: 8,
    calories_g: 208,
    estimated_grams: 250,
    aliases: ['choc milk', 'chocolate milk drink', 'choco milk', 'flavoured milk chocolate'],
  },
  { name: 'Strawberry milk', portion: '1 cup', protein_g: 8, calories_g: 180, estimated_grams: 250 },
  {
    name: 'Hot chocolate',
    portion: '1 cup',
    protein_g: 8,
    calories_g: 190,
    estimated_grams: 250,
    aliases: ['hot cocoa', 'hot choc', 'drinking chocolate', 'cocoa drink'],
  },
  { name: 'Almond milk', portion: '1 cup', protein_g: 1, calories_g: 39, estimated_grams: 240, aliases: ['unsweetened almond milk'] },
  { name: 'Sweetened almond milk', portion: '1 cup', protein_g: 1, calories_g: 60, estimated_grams: 240 },
  { name: 'Oat milk', portion: '1 cup', protein_g: 3, calories_g: 120, estimated_grams: 240, aliases: ['oatly', 'oat drink'] },
  { name: 'Soy milk', portion: '1 cup', protein_g: 7, calories_g: 100, estimated_grams: 243, aliases: ['soya milk', 'soy drink'] },
  { name: 'Coconut milk (carton)', portion: '1 cup', protein_g: 0.5, calories_g: 45, estimated_grams: 240, aliases: ['coconut milk drink'] },
  { name: 'Coconut milk (canned)', portion: '0.5 cup', protein_g: 2.3, calories_g: 223, estimated_grams: 120 },
  { name: 'Rice milk', portion: '1 cup', protein_g: 0.7, calories_g: 113, estimated_grams: 240 },
  { name: 'Cashew milk', portion: '1 cup', protein_g: 1, calories_g: 25, estimated_grams: 240 },
  { name: 'Hemp milk', portion: '1 cup', protein_g: 3, calories_g: 70, estimated_grams: 240 },
  { name: 'Pea milk', portion: '1 cup', protein_g: 8, calories_g: 70, estimated_grams: 240 },
  { name: 'Macadamia milk', portion: '1 cup', protein_g: 1, calories_g: 50, estimated_grams: 240 },
  { name: 'Flax milk', portion: '1 cup', protein_g: 0, calories_g: 25, estimated_grams: 240 },
  { name: 'Hazelnut milk', portion: '1 cup', protein_g: 1, calories_g: 70, estimated_grams: 240 },
  { name: 'Cream', portion: '2 tbsp', protein_g: 0.5, calories_g: 100, estimated_grams: 30 },
  { name: 'Double cream', portion: '2 tbsp', protein_g: 0.5, calories_g: 135, estimated_grams: 30, aliases: ['heavy cream', 'whipping cream'] },
  { name: 'Single cream', portion: '2 tbsp', protein_g: 0.5, calories_g: 55, estimated_grams: 30, aliases: ['light cream'] },
  { name: 'Sour cream', portion: '2 tbsp', protein_g: 0.7, calories_g: 46, estimated_grams: 30 },
  { name: 'Clotted cream', portion: '1 tbsp', protein_g: 0.4, calories_g: 70, estimated_grams: 15 },
  { name: 'Half and half', portion: '2 tbsp', protein_g: 0.7, calories_g: 40, estimated_grams: 30 },
  { name: 'Whipped cream', portion: '2 tbsp', protein_g: 0.3, calories_g: 50, estimated_grams: 15 },
  { name: 'Creme fraiche', portion: '2 tbsp', protein_g: 0.8, calories_g: 70, estimated_grams: 30 },
  { name: 'Kefir', portion: '1 cup', protein_g: 9, calories_g: 110, estimated_grams: 245 },
  { name: 'Lassi', portion: '1 glass', protein_g: 6, calories_g: 150, estimated_grams: 250 },
  { name: 'Mango lassi', portion: '1 glass', protein_g: 6, calories_g: 220, estimated_grams: 280 },
  { name: 'Skyr', portion: '1 serving', protein_g: 17, calories_g: 100, estimated_grams: 150 },
  { name: 'Quark', portion: '1 serving', protein_g: 12, calories_g: 80, estimated_grams: 100 },
  { name: 'Ricotta', portion: '2 tbsp', protein_g: 3.5, calories_g: 50, estimated_grams: 30 },
  { name: 'Mascarpone', portion: '2 tbsp', protein_g: 1.5, calories_g: 120, estimated_grams: 30 },
  { name: 'Cream cheese', portion: '2 tbsp', protein_g: 2, calories_g: 100, estimated_grams: 30 },
  { name: 'Feta', portion: '1 serving', protein_g: 4, calories_g: 75, estimated_grams: 28 },
  { name: 'Goat cheese', portion: '1 serving', protein_g: 5, calories_g: 75, estimated_grams: 28 },
  { name: 'Parmesan', portion: '1 tbsp', protein_g: 3.8, calories_g: 22, estimated_grams: 5 },
  { name: 'Blue cheese', portion: '1 serving', protein_g: 6, calories_g: 100, estimated_grams: 28 },
  { name: 'Brie', portion: '1 serving', protein_g: 5, calories_g: 95, estimated_grams: 28 },
  { name: 'Camembert', portion: '1 serving', protein_g: 5, calories_g: 85, estimated_grams: 28 },
  { name: 'Swiss cheese', portion: '1 slice', protein_g: 8, calories_g: 110, estimated_grams: 28 },
  { name: 'Provolone', portion: '1 slice', protein_g: 7, calories_g: 100, estimated_grams: 28 },
  { name: 'Halloumi', portion: '1 serving', protein_g: 14, calories_g: 180, estimated_grams: 60 },
  { name: 'String cheese', portion: '1 stick', protein_g: 6, calories_g: 80, estimated_grams: 28 },
  { name: 'Processed cheese', portion: '1 slice', protein_g: 4, calories_g: 70, estimated_grams: 20, aliases: ['american cheese', 'cheese singles'] },
  { name: 'Labneh', portion: '2 tbsp', protein_g: 2.5, calories_g: 50, estimated_grams: 30 },
  { name: 'Fromage frais', portion: '1 serving', protein_g: 6, calories_g: 70, estimated_grams: 100 },
  { name: 'Custard', portion: '0.5 cup', protein_g: 4, calories_g: 140, estimated_grams: 120 },
  { name: 'Ice cream (vanilla)', portion: '1 scoop', protein_g: 3, calories_g: 140, estimated_grams: 70 },
  { name: 'Ice cream (chocolate)', portion: '1 scoop', protein_g: 3, calories_g: 150, estimated_grams: 70 },
  { name: 'Gelato', portion: '1 scoop', protein_g: 3, calories_g: 160, estimated_grams: 70 },
  { name: 'Frozen yogurt', portion: '1 scoop', protein_g: 4, calories_g: 110, estimated_grams: 80 },
  { name: 'Milkshake', portion: '1 glass', protein_g: 9, calories_g: 350, estimated_grams: 300 },
  { name: 'Protein yogurt', portion: '1 pot', protein_g: 15, calories_g: 120, estimated_grams: 150 },
  { name: 'Low-fat yogurt', portion: '1 serving', protein_g: 6, calories_g: 70, estimated_grams: 150 },
  { name: 'Full-fat yogurt', portion: '1 serving', protein_g: 5, calories_g: 110, estimated_grams: 150 },
  { name: 'Greek yogurt (0%)', portion: '1 serving', protein_g: 17, calories_g: 90, estimated_grams: 170 },
  { name: 'Greek yogurt (full fat)', portion: '1 serving', protein_g: 9, calories_g: 150, estimated_grams: 170 },
  { name: 'Drinkable yogurt', portion: '1 bottle', protein_g: 6, calories_g: 140, estimated_grams: 200 },

  // —— Eggs ——
  { name: 'Egg yolk', portion: '1 yolk', protein_g: 2.7, calories_g: 55, estimated_grams: 17 },
  { name: 'Fried egg', portion: '1 egg', protein_g: 6.3, calories_g: 90, estimated_grams: 50 },
  { name: 'Poached egg', portion: '1 egg', protein_g: 6.3, calories_g: 72, estimated_grams: 50 },
  { name: 'Deviled egg', portion: '1 half', protein_g: 3.1, calories_g: 60, estimated_grams: 30 },
  { name: 'Egg bite', portion: '1 bite', protein_g: 5, calories_g: 70, estimated_grams: 40 },
  { name: 'Duck egg', portion: '1 egg', protein_g: 9, calories_g: 130, estimated_grams: 70 },
  { name: 'Quail egg', portion: '1 egg', protein_g: 1.2, calories_g: 14, estimated_grams: 9 },

  // —— Chicken / poultry ——
  { name: 'Grilled chicken', portion: '1 serving', protein_g: 31, calories_g: 165, estimated_grams: 100 },
  { name: 'Chicken breast (grilled)', portion: '1 serving', protein_g: 31, calories_g: 165, estimated_grams: 100 },
  { name: 'Chicken breast (fried)', portion: '1 serving', protein_g: 28, calories_g: 250, estimated_grams: 100 },
  { name: 'Chicken tenders', portion: '1 piece', protein_g: 8, calories_g: 100, estimated_grams: 35 },
  { name: 'Chicken nuggets', portion: '1 nugget', protein_g: 2.5, calories_g: 45, estimated_grams: 16 },
  { name: 'Chicken strips', portion: '1 strip', protein_g: 8, calories_g: 90, estimated_grams: 35 },
  { name: 'Rotisserie chicken', portion: '1 serving', protein_g: 25, calories_g: 190, estimated_grams: 100 },
  { name: 'Chicken drumstick', portion: '1 drumstick', protein_g: 12, calories_g: 110, estimated_grams: 50 },
  { name: 'Chicken leg', portion: '1 leg', protein_g: 20, calories_g: 180, estimated_grams: 100 },
  { name: 'Chicken kebab', portion: '1 skewer', protein_g: 20, calories_g: 180, estimated_grams: 100 },
  { name: 'Chicken tikka', portion: '1 serving', protein_g: 25, calories_g: 200, estimated_grams: 120 },
  { name: 'Chicken tikka masala', portion: '1 bowl', protein_g: 24, calories_g: 350, estimated_grams: 250 },
  { name: 'Butter chicken', portion: '1 bowl', protein_g: 22, calories_g: 380, estimated_grams: 250 },
  { name: 'Chicken shawarma', portion: '1 wrap', protein_g: 28, calories_g: 450, estimated_grams: 280 },
  { name: 'Turkey breast', portion: '1 serving', protein_g: 29, calories_g: 135, estimated_grams: 100 },
  { name: 'Turkey slices', portion: '1 slice', protein_g: 5, calories_g: 30, estimated_grams: 20 },
  { name: 'Duck', portion: '1 serving', protein_g: 19, calories_g: 340, estimated_grams: 100 },
  { name: 'Ground chicken', portion: '1 serving', protein_g: 23, calories_g: 140, estimated_grams: 100 },
  { name: 'Ground turkey', portion: '1 serving', protein_g: 27, calories_g: 170, estimated_grams: 100 },

  // —— Red meat / pork ——
  { name: 'Steak', portion: '1 steak', protein_g: 40, calories_g: 350, estimated_grams: 150 },
  { name: 'Sirloin steak', portion: '1 steak', protein_g: 40, calories_g: 320, estimated_grams: 150 },
  { name: 'Ribeye steak', portion: '1 steak', protein_g: 36, calories_g: 400, estimated_grams: 150 },
  { name: 'Minced beef', portion: '1 serving', protein_g: 26, calories_g: 250, estimated_grams: 100, aliases: ['ground beef', 'beef mince'] },
  { name: 'Lean minced beef', portion: '1 serving', protein_g: 27, calories_g: 180, estimated_grams: 100 },
  { name: 'Beef burger patty', portion: '1 patty', protein_g: 20, calories_g: 250, estimated_grams: 100 },
  { name: 'Roast beef', portion: '1 slice', protein_g: 8, calories_g: 50, estimated_grams: 30 },
  { name: 'Beef jerky', portion: '1 serving', protein_g: 10, calories_g: 80, estimated_grams: 28 },
  { name: 'Lamb chops', portion: '1 chop', protein_g: 18, calories_g: 220, estimated_grams: 70 },
  { name: 'Lamb kebab', portion: '1 skewer', protein_g: 22, calories_g: 250, estimated_grams: 100 },
  { name: 'Pork chop', portion: '1 chop', protein_g: 26, calories_g: 220, estimated_grams: 100 },
  { name: 'Pork belly', portion: '1 serving', protein_g: 15, calories_g: 350, estimated_grams: 80 },
  { name: 'Pulled pork', portion: '1 serving', protein_g: 23, calories_g: 250, estimated_grams: 100 },
  { name: 'Ham slices', portion: '1 slice', protein_g: 5, calories_g: 35, estimated_grams: 25 },
  { name: 'Prosciutto', portion: '1 slice', protein_g: 4, calories_g: 35, estimated_grams: 15 },
  { name: 'Salami', portion: '1 slice', protein_g: 2.5, calories_g: 45, estimated_grams: 10 },
  { name: 'Pepperoni', portion: '1 slice', protein_g: 2, calories_g: 30, estimated_grams: 6 },
  { name: 'Chorizo', portion: '1 serving', protein_g: 8, calories_g: 150, estimated_grams: 40 },
  { name: 'Bratwurst', portion: '1 sausage', protein_g: 12, calories_g: 250, estimated_grams: 80 },
  { name: 'Hot dog', portion: '1 hot dog', protein_g: 7, calories_g: 150, estimated_grams: 50 },
  { name: 'Corned beef', portion: '1 serving', protein_g: 18, calories_g: 180, estimated_grams: 70 },
  { name: 'Veal', portion: '1 serving', protein_g: 28, calories_g: 170, estimated_grams: 100 },
  { name: 'Venison', portion: '1 serving', protein_g: 30, calories_g: 160, estimated_grams: 100 },

  // —— Fish / seafood ——
  { name: 'Cod', portion: '1 fillet', protein_g: 20, calories_g: 90, estimated_grams: 100 },
  { name: 'Haddock', portion: '1 fillet', protein_g: 20, calories_g: 95, estimated_grams: 100 },
  { name: 'Tilapia', portion: '1 fillet', protein_g: 21, calories_g: 100, estimated_grams: 100 },
  { name: 'Sea bass', portion: '1 fillet', protein_g: 20, calories_g: 120, estimated_grams: 100 },
  { name: 'Mackerel', portion: '1 fillet', protein_g: 19, calories_g: 200, estimated_grams: 100 },
  { name: 'Sardines', portion: '1 can', protein_g: 23, calories_g: 190, estimated_grams: 90 },
  { name: 'Anchovies', portion: '1 serving', protein_g: 6, calories_g: 40, estimated_grams: 20 },
  { name: 'Trout', portion: '1 fillet', protein_g: 21, calories_g: 150, estimated_grams: 100 },
  { name: 'Smoked salmon', portion: '1 serving', protein_g: 18, calories_g: 120, estimated_grams: 70 },
  { name: 'Tuna steak', portion: '1 steak', protein_g: 30, calories_g: 140, estimated_grams: 100 },
  { name: 'Canned tuna', portion: '1 can', protein_g: 25, calories_g: 110, estimated_grams: 100, aliases: ['tuna in brine', 'tuna in water'] },
  { name: 'Tuna in oil', portion: '1 can', protein_g: 25, calories_g: 190, estimated_grams: 100 },
  { name: 'Crab', portion: '1 serving', protein_g: 18, calories_g: 90, estimated_grams: 100 },
  { name: 'Lobster', portion: '1 serving', protein_g: 19, calories_g: 90, estimated_grams: 100 },
  { name: 'Scallops', portion: '1 serving', protein_g: 17, calories_g: 90, estimated_grams: 85 },
  { name: 'Mussels', portion: '1 serving', protein_g: 12, calories_g: 90, estimated_grams: 100 },
  { name: 'Oysters', portion: '1 oyster', protein_g: 1, calories_g: 8, estimated_grams: 15 },
  { name: 'Calamari', portion: '1 serving', protein_g: 15, calories_g: 150, estimated_grams: 85 },
  { name: 'Fish and chips', portion: '1 serving', protein_g: 25, calories_g: 600, estimated_grams: 350 },
  { name: 'Fish fingers', portion: '1 finger', protein_g: 3, calories_g: 50, estimated_grams: 25 },
  { name: 'Sushi roll', portion: '1 roll', protein_g: 8, calories_g: 250, estimated_grams: 150 },
  { name: 'Sashimi', portion: '1 piece', protein_g: 4, calories_g: 30, estimated_grams: 20 },
  { name: 'Poke bowl', portion: '1 bowl', protein_g: 30, calories_g: 450, estimated_grams: 400 },

  // —— Plant proteins ——
  { name: 'Firm tofu', portion: '1 serving', protein_g: 10, calories_g: 90, estimated_grams: 100 },
  { name: 'Silken tofu', portion: '1 serving', protein_g: 6, calories_g: 55, estimated_grams: 100 },
  { name: 'Edamame', portion: '1 serving', protein_g: 11, calories_g: 120, estimated_grams: 100 },
  { name: 'Seitan', portion: '1 serving', protein_g: 25, calories_g: 120, estimated_grams: 85 },
  { name: 'Beyond burger', portion: '1 patty', protein_g: 20, calories_g: 250, estimated_grams: 113 },
  { name: 'Impossible burger', portion: '1 patty', protein_g: 19, calories_g: 240, estimated_grams: 113 },
  { name: 'Veggie burger', portion: '1 patty', protein_g: 12, calories_g: 180, estimated_grams: 100 },
  { name: 'Falafel', portion: '1 piece', protein_g: 2.5, calories_g: 60, estimated_grams: 20 },
  { name: 'Lentil dal', portion: '1 bowl', protein_g: 9, calories_g: 160, estimated_grams: 200 },
  { name: 'Moong dal', portion: '1 bowl', protein_g: 8, calories_g: 140, estimated_grams: 180 },
  { name: 'Toor dal', portion: '1 bowl', protein_g: 8, calories_g: 150, estimated_grams: 180 },
  { name: 'Chana dal', portion: '1 bowl', protein_g: 9, calories_g: 160, estimated_grams: 180 },
  { name: 'Kidney beans', portion: '1 serving', protein_g: 8, calories_g: 130, estimated_grams: 100 },
  { name: 'Baked beans', portion: '1 serving', protein_g: 6, calories_g: 120, estimated_grams: 150 },
  { name: 'Refried beans', portion: '1 serving', protein_g: 7, calories_g: 140, estimated_grams: 120 },
  { name: 'White beans', portion: '1 serving', protein_g: 8, calories_g: 130, estimated_grams: 100 },
  { name: 'Pinto beans', portion: '1 serving', protein_g: 8, calories_g: 140, estimated_grams: 100 },
  { name: 'Split peas', portion: '1 serving', protein_g: 8, calories_g: 120, estimated_grams: 100 },

  // —— Grains / carbs ——
  { name: 'Basmati rice', portion: '1 cup', protein_g: 4, calories_g: 190, estimated_grams: 150 },
  { name: 'Jasmine rice', portion: '1 cup', protein_g: 4, calories_g: 200, estimated_grams: 150 },
  { name: 'Sushi rice', portion: '1 cup', protein_g: 3.5, calories_g: 240, estimated_grams: 150 },
  { name: 'Wild rice', portion: '1 cup', protein_g: 6.5, calories_g: 165, estimated_grams: 160 },
  { name: 'Couscous', portion: '1 cup', protein_g: 6, calories_g: 175, estimated_grams: 150 },
  { name: 'Bulgur', portion: '1 cup', protein_g: 6, calories_g: 150, estimated_grams: 140 },
  { name: 'Barley', portion: '1 cup', protein_g: 4, calories_g: 190, estimated_grams: 150 },
  { name: 'Farro', portion: '1 cup', protein_g: 6, calories_g: 170, estimated_grams: 150 },
  { name: 'Millet', portion: '1 cup', protein_g: 6, calories_g: 210, estimated_grams: 170 },
  { name: 'Polenta', portion: '1 serving', protein_g: 3, calories_g: 140, estimated_grams: 150 },
  { name: 'Grits', portion: '1 serving', protein_g: 3, calories_g: 150, estimated_grams: 150 },
  { name: 'Congee', portion: '1 bowl', protein_g: 3, calories_g: 120, estimated_grams: 250 },
  { name: 'Risotto', portion: '1 bowl', protein_g: 7, calories_g: 320, estimated_grams: 250 },
  { name: 'Porridge', portion: '1 bowl', protein_g: 5, calories_g: 160, estimated_grams: 200, aliases: ['oatmeal porridge'] },
  { name: 'Overnight oats', portion: '1 serving', protein_g: 10, calories_g: 280, estimated_grams: 250 },
  { name: 'Steel-cut oats', portion: '1 serving', protein_g: 5, calories_g: 150, estimated_grams: 40 },
  { name: 'Rolled oats', portion: '1 serving', protein_g: 5, calories_g: 150, estimated_grams: 40 },
  { name: 'Instant oats', portion: '1 packet', protein_g: 4, calories_g: 130, estimated_grams: 35 },
  { name: 'Muesli', portion: '1 serving', protein_g: 5, calories_g: 180, estimated_grams: 50 },
  { name: 'Cornflakes', portion: '1 bowl', protein_g: 2, calories_g: 100, estimated_grams: 30 },
  { name: 'Weetabix', portion: '2 biscuits', protein_g: 4.5, calories_g: 130, estimated_grams: 40 },
  { name: 'Shredded wheat', portion: '2 biscuits', protein_g: 5, calories_g: 140, estimated_grams: 45 },
  { name: 'Penne', portion: '1 serving', protein_g: 7, calories_g: 220, estimated_grams: 140 },
  { name: 'Fusilli', portion: '1 serving', protein_g: 7, calories_g: 220, estimated_grams: 140 },
  { name: 'Macaroni', portion: '1 serving', protein_g: 7, calories_g: 220, estimated_grams: 140 },
  { name: 'Mac and cheese', portion: '1 bowl', protein_g: 12, calories_g: 400, estimated_grams: 250 },
  { name: 'Lasagna', portion: '1 serving', protein_g: 20, calories_g: 400, estimated_grams: 250 },
  { name: 'Ravioli', portion: '1 serving', protein_g: 12, calories_g: 280, estimated_grams: 180 },
  { name: 'Gnocchi', portion: '1 serving', protein_g: 6, calories_g: 250, estimated_grams: 180 },
  { name: 'Udon', portion: '1 bowl', protein_g: 8, calories_g: 300, estimated_grams: 300 },
  { name: 'Soba', portion: '1 bowl', protein_g: 10, calories_g: 250, estimated_grams: 250 },
  { name: 'Rice noodles', portion: '1 serving', protein_g: 2, calories_g: 190, estimated_grams: 140 },
  { name: 'Egg noodles', portion: '1 serving', protein_g: 7, calories_g: 220, estimated_grams: 140 },
  { name: 'Instant noodles', portion: '1 pack', protein_g: 8, calories_g: 380, estimated_grams: 85 },
  { name: 'Tortilla', portion: '1 tortilla', protein_g: 4, calories_g: 140, estimated_grams: 50 },
  { name: 'Flour tortilla', portion: '1 tortilla', protein_g: 4, calories_g: 140, estimated_grams: 50 },
  { name: 'Corn tortilla', portion: '1 tortilla', protein_g: 1.5, calories_g: 50, estimated_grams: 25 },
  { name: 'Pita bread', portion: '1 pita', protein_g: 5, calories_g: 165, estimated_grams: 60 },
  { name: 'Sourdough', portion: '1 slice', protein_g: 4, calories_g: 100, estimated_grams: 40 },
  { name: 'Whole wheat bread', portion: '1 slice', protein_g: 4, calories_g: 80, estimated_grams: 35 },
  { name: 'White bread', portion: '1 slice', protein_g: 2.5, calories_g: 75, estimated_grams: 30 },
  { name: 'Brown bread', portion: '1 slice', protein_g: 3.5, calories_g: 80, estimated_grams: 35 },
  { name: 'Multigrain bread', portion: '1 slice', protein_g: 4, calories_g: 90, estimated_grams: 35 },
  { name: 'Rye bread', portion: '1 slice', protein_g: 3, calories_g: 80, estimated_grams: 35 },
  { name: 'English muffin', portion: '1 muffin', protein_g: 4, calories_g: 130, estimated_grams: 57 },
  { name: 'Crumpet', portion: '1 crumpet', protein_g: 3, calories_g: 90, estimated_grams: 40 },
  { name: 'Brioche', portion: '1 slice', protein_g: 4, calories_g: 150, estimated_grams: 40 },
  { name: 'Ciabatta', portion: '1 serving', protein_g: 6, calories_g: 180, estimated_grams: 60 },
  { name: 'Baguette', portion: '1 slice', protein_g: 3, calories_g: 90, estimated_grams: 35 },
  { name: 'Garlic bread', portion: '1 slice', protein_g: 3, calories_g: 150, estimated_grams: 40 },
  { name: 'Dinner roll', portion: '1 roll', protein_g: 3, calories_g: 100, estimated_grams: 35 },
  { name: 'Bun', portion: '1 bun', protein_g: 4, calories_g: 140, estimated_grams: 50 },
  { name: 'Burger bun', portion: '1 bun', protein_g: 5, calories_g: 150, estimated_grams: 55 },
  { name: 'Hot dog bun', portion: '1 bun', protein_g: 4, calories_g: 120, estimated_grams: 45 },

  // —— Potatoes / sides ——
  { name: 'Mashed potato', portion: '1 serving', protein_g: 3, calories_g: 170, estimated_grams: 180 },
  { name: 'Baked potato', portion: '1 potato', protein_g: 4, calories_g: 160, estimated_grams: 170 },
  { name: 'Jacket potato', portion: '1 potato', protein_g: 4, calories_g: 160, estimated_grams: 170 },
  { name: 'Roast potatoes', portion: '1 serving', protein_g: 3, calories_g: 200, estimated_grams: 120 },
  { name: 'Boiled potatoes', portion: '1 serving', protein_g: 3, calories_g: 120, estimated_grams: 150 },
  { name: 'Chips', portion: '1 serving', protein_g: 3, calories_g: 320, estimated_grams: 100, aliases: ['potato chips', 'crisps'] },
  { name: 'Sweet potato fries', portion: '1 serving', protein_g: 2, calories_g: 200, estimated_grams: 100 },
  { name: 'Tater tots', portion: '1 serving', protein_g: 2, calories_g: 160, estimated_grams: 70 },
  { name: 'Onion rings', portion: '1 serving', protein_g: 3, calories_g: 250, estimated_grams: 80 },

  // —— Fruit ——
  { name: 'Pear', portion: '1 pear', protein_g: 0.6, calories_g: 100, estimated_grams: 180 },
  { name: 'Peach', portion: '1 peach', protein_g: 1, calories_g: 60, estimated_grams: 150 },
  { name: 'Plum', portion: '1 plum', protein_g: 0.5, calories_g: 30, estimated_grams: 66 },
  { name: 'Cherry', portion: '1 serving', protein_g: 1, calories_g: 60, estimated_grams: 100 },
  { name: 'Kiwi', portion: '1 kiwi', protein_g: 1, calories_g: 42, estimated_grams: 75 },
  { name: 'Papaya', portion: '1 serving', protein_g: 0.7, calories_g: 55, estimated_grams: 140 },
  { name: 'Guava', portion: '1 guava', protein_g: 2.5, calories_g: 70, estimated_grams: 100 },
  { name: 'Pomegranate', portion: '0.5 fruit', protein_g: 1.5, calories_g: 80, estimated_grams: 100 },
  { name: 'Fig', portion: '1 fig', protein_g: 0.4, calories_g: 37, estimated_grams: 40 },
  { name: 'Dates', portion: '2 dates', protein_g: 0.4, calories_g: 66, estimated_grams: 20 },
  { name: 'Raisins', portion: '1 handful', protein_g: 0.8, calories_g: 85, estimated_grams: 28 },
  { name: 'Dried cranberries', portion: '1 handful', protein_g: 0.1, calories_g: 90, estimated_grams: 28 },
  { name: 'Coconut', portion: '1 serving', protein_g: 2, calories_g: 150, estimated_grams: 45 },
  { name: 'Lemon', portion: '1 lemon', protein_g: 0.6, calories_g: 17, estimated_grams: 58 },
  { name: 'Lime', portion: '1 lime', protein_g: 0.5, calories_g: 20, estimated_grams: 67 },
  { name: 'Grapefruit', portion: '0.5 fruit', protein_g: 0.8, calories_g: 40, estimated_grams: 120 },
  { name: 'Cantaloupe', portion: '1 serving', protein_g: 0.8, calories_g: 50, estimated_grams: 150 },
  { name: 'Honeydew', portion: '1 serving', protein_g: 0.8, calories_g: 60, estimated_grams: 150 },
  { name: 'Raspberries', portion: '1 serving', protein_g: 1.2, calories_g: 50, estimated_grams: 100 },
  { name: 'Blackberries', portion: '1 serving', protein_g: 1.4, calories_g: 43, estimated_grams: 100 },
  { name: 'Cranberries', portion: '1 serving', protein_g: 0.4, calories_g: 46, estimated_grams: 100 },
  { name: 'Passion fruit', portion: '1 fruit', protein_g: 0.5, calories_g: 17, estimated_grams: 18 },
  { name: 'Dragon fruit', portion: '1 serving', protein_g: 1, calories_g: 60, estimated_grams: 150 },
  { name: 'Lychee', portion: '5 lychees', protein_g: 0.7, calories_g: 60, estimated_grams: 50 },
  { name: 'Jackfruit', portion: '1 serving', protein_g: 1.7, calories_g: 95, estimated_grams: 100 },
  { name: 'Plantain', portion: '1 plantain', protein_g: 1.3, calories_g: 180, estimated_grams: 180 },
  { name: 'Fruit salad', portion: '1 bowl', protein_g: 1.5, calories_g: 90, estimated_grams: 150 },
  { name: 'Mixed berries', portion: '1 serving', protein_g: 1, calories_g: 50, estimated_grams: 100 },
  { name: 'Dried mango', portion: '1 serving', protein_g: 0.5, calories_g: 120, estimated_grams: 40 },

  // —— Vegetables ——
  { name: 'Bell pepper', portion: '1 pepper', protein_g: 1, calories_g: 30, estimated_grams: 120, aliases: ['capsicum'] },
  { name: 'Zucchini', portion: '1 serving', protein_g: 1.2, calories_g: 20, estimated_grams: 100, aliases: ['courgette'] },
  { name: 'Aubergine', portion: '1 serving', protein_g: 1, calories_g: 25, estimated_grams: 100, aliases: ['eggplant'] },
  { name: 'Cauliflower', portion: '1 serving', protein_g: 2, calories_g: 25, estimated_grams: 100 },
  { name: 'Cabbage', portion: '1 serving', protein_g: 1.3, calories_g: 25, estimated_grams: 100 },
  { name: 'Kale', portion: '1 serving', protein_g: 2.9, calories_g: 35, estimated_grams: 70 },
  { name: 'Asparagus', portion: '1 serving', protein_g: 2.2, calories_g: 20, estimated_grams: 90 },
  { name: 'Green beans', portion: '1 serving', protein_g: 1.8, calories_g: 30, estimated_grams: 100 },
  { name: 'Brussels sprouts', portion: '1 serving', protein_g: 3.4, calories_g: 45, estimated_grams: 100 },
  { name: 'Beetroot', portion: '1 serving', protein_g: 1.6, calories_g: 45, estimated_grams: 100 },
  { name: 'Radish', portion: '1 serving', protein_g: 0.7, calories_g: 16, estimated_grams: 100 },
  { name: 'Celery', portion: '1 stalk', protein_g: 0.3, calories_g: 6, estimated_grams: 40 },
  { name: 'Leek', portion: '1 serving', protein_g: 1.5, calories_g: 60, estimated_grams: 100 },
  { name: 'Spring onion', portion: '1 serving', protein_g: 0.9, calories_g: 16, estimated_grams: 50 },
  { name: 'Ginger', portion: '1 tsp', protein_g: 0.1, calories_g: 2, estimated_grams: 5 },
  { name: 'Chilli', portion: '1 chilli', protein_g: 0.2, calories_g: 4, estimated_grams: 10 },
  { name: 'Jalapeno', portion: '1 pepper', protein_g: 0.2, calories_g: 4, estimated_grams: 14 },
  { name: 'Pumpkin', portion: '1 serving', protein_g: 1, calories_g: 30, estimated_grams: 100 },
  { name: 'Butternut squash', portion: '1 serving', protein_g: 1, calories_g: 45, estimated_grams: 100 },
  { name: 'Okra', portion: '1 serving', protein_g: 2, calories_g: 30, estimated_grams: 100, aliases: ['bhindi'] },
  { name: 'Bitter gourd', portion: '1 serving', protein_g: 1, calories_g: 20, estimated_grams: 100 },
  { name: 'Bottle gourd', portion: '1 serving', protein_g: 0.6, calories_g: 15, estimated_grams: 100, aliases: ['lauki'] },
  { name: 'Drumstick vegetable', portion: '1 serving', protein_g: 2, calories_g: 35, estimated_grams: 100 },
  { name: 'Mixed vegetables', portion: '1 serving', protein_g: 2, calories_g: 50, estimated_grams: 100 },
  { name: 'Stir fry vegetables', portion: '1 serving', protein_g: 3, calories_g: 80, estimated_grams: 150 },
  { name: 'Coleslaw', portion: '1 serving', protein_g: 1, calories_g: 150, estimated_grams: 100 },
  { name: 'Kimchi', portion: '1 serving', protein_g: 1.5, calories_g: 20, estimated_grams: 50 },
  { name: 'Sauerkraut', portion: '1 serving', protein_g: 1, calories_g: 20, estimated_grams: 70 },
  { name: 'Pickles', portion: '1 pickle', protein_g: 0.2, calories_g: 5, estimated_grams: 30 },
  { name: 'Olives', portion: '5 olives', protein_g: 0.3, calories_g: 30, estimated_grams: 20 },
  { name: 'Sun-dried tomatoes', portion: '1 serving', protein_g: 2, calories_g: 60, estimated_grams: 20 },

  // —— Nuts / seeds ——
  { name: 'Pistachios', portion: '1 handful', protein_g: 6, calories_g: 160, estimated_grams: 28 },
  { name: 'Macadamia nuts', portion: '1 handful', protein_g: 2, calories_g: 200, estimated_grams: 28 },
  { name: 'Brazil nuts', portion: '3 nuts', protein_g: 4, calories_g: 185, estimated_grams: 28 },
  { name: 'Pecans', portion: '1 handful', protein_g: 2.5, calories_g: 190, estimated_grams: 28 },
  { name: 'Hazelnuts', portion: '1 handful', protein_g: 4, calories_g: 180, estimated_grams: 28 },
  { name: 'Mixed nuts', portion: '1 handful', protein_g: 5, calories_g: 170, estimated_grams: 28 },
  { name: 'Trail mix', portion: '1 handful', protein_g: 4, calories_g: 180, estimated_grams: 30 },
  { name: 'Chia seeds', portion: '1 tbsp', protein_g: 2, calories_g: 60, estimated_grams: 12 },
  { name: 'Flax seeds', portion: '1 tbsp', protein_g: 1.9, calories_g: 55, estimated_grams: 10 },
  { name: 'Pumpkin seeds', portion: '1 handful', protein_g: 7, calories_g: 150, estimated_grams: 28 },
  { name: 'Sunflower seeds', portion: '1 handful', protein_g: 6, calories_g: 160, estimated_grams: 28 },
  { name: 'Sesame seeds', portion: '1 tbsp', protein_g: 1.6, calories_g: 50, estimated_grams: 9 },
  { name: 'Hemp seeds', portion: '1 tbsp', protein_g: 3, calories_g: 55, estimated_grams: 10 },
  { name: 'Almond butter', portion: '1 tbsp', protein_g: 3.4, calories_g: 98, estimated_grams: 16 },
  { name: 'Cashew butter', portion: '1 tbsp', protein_g: 2.8, calories_g: 94, estimated_grams: 16 },
  { name: 'Tahini', portion: '1 tbsp', protein_g: 2.6, calories_g: 89, estimated_grams: 15 },
  { name: 'Nutella', portion: '1 tbsp', protein_g: 1, calories_g: 100, estimated_grams: 19 },

  // —— Oils / fats / condiments ——
  { name: 'Vegetable oil', portion: '1 tbsp', protein_g: 0, calories_g: 120, estimated_grams: 14 },
  { name: 'Sunflower oil', portion: '1 tbsp', protein_g: 0, calories_g: 120, estimated_grams: 14 },
  { name: 'Coconut oil', portion: '1 tbsp', protein_g: 0, calories_g: 120, estimated_grams: 14 },
  { name: 'Sesame oil', portion: '1 tsp', protein_g: 0, calories_g: 40, estimated_grams: 5 },
  { name: 'Avocado oil', portion: '1 tbsp', protein_g: 0, calories_g: 120, estimated_grams: 14 },
  { name: 'Rapeseed oil', portion: '1 tbsp', protein_g: 0, calories_g: 120, estimated_grams: 14, aliases: ['canola oil'] },
  { name: 'Margarine', portion: '1 tsp', protein_g: 0, calories_g: 35, estimated_grams: 5 },
  { name: 'Mustard', portion: '1 tsp', protein_g: 0.3, calories_g: 5, estimated_grams: 5 },
  { name: 'Hot sauce', portion: '1 tsp', protein_g: 0, calories_g: 1, estimated_grams: 5 },
  { name: 'BBQ sauce', portion: '1 tbsp', protein_g: 0.2, calories_g: 30, estimated_grams: 17 },
  { name: 'Ranch dressing', portion: '1 tbsp', protein_g: 0.2, calories_g: 70, estimated_grams: 15 },
  { name: 'Caesar dressing', portion: '1 tbsp', protein_g: 0.3, calories_g: 80, estimated_grams: 15 },
  { name: 'Vinaigrette', portion: '1 tbsp', protein_g: 0, calories_g: 45, estimated_grams: 15 },
  { name: 'Pesto', portion: '1 tbsp', protein_g: 1.5, calories_g: 80, estimated_grams: 15 },
  { name: 'Tomato sauce', portion: '2 tbsp', protein_g: 0.8, calories_g: 20, estimated_grams: 30 },
  { name: 'Tomato puree', portion: '1 tbsp', protein_g: 0.5, calories_g: 10, estimated_grams: 15 },
  { name: 'Passata', portion: '0.5 cup', protein_g: 1.5, calories_g: 35, estimated_grams: 100 },
  { name: 'Gravy', portion: '2 tbsp', protein_g: 0.5, calories_g: 25, estimated_grams: 30 },
  { name: 'Stock', portion: '1 cup', protein_g: 1, calories_g: 15, estimated_grams: 240, aliases: ['broth'] },
  { name: 'Chicken stock', portion: '1 cup', protein_g: 1, calories_g: 15, estimated_grams: 240 },
  { name: 'Vegetable stock', portion: '1 cup', protein_g: 0.5, calories_g: 10, estimated_grams: 240 },
  { name: 'Worcestershire sauce', portion: '1 tsp', protein_g: 0, calories_g: 5, estimated_grams: 5 },
  { name: 'Fish sauce', portion: '1 tsp', protein_g: 0.5, calories_g: 3, estimated_grams: 5 },
  { name: 'Oyster sauce', portion: '1 tbsp', protein_g: 0.5, calories_g: 20, estimated_grams: 16 },
  { name: 'Teriyaki sauce', portion: '1 tbsp', protein_g: 1, calories_g: 30, estimated_grams: 16 },
  { name: 'Sriracha', portion: '1 tsp', protein_g: 0.1, calories_g: 5, estimated_grams: 5 },
  { name: 'Chilli sauce', portion: '1 tbsp', protein_g: 0.2, calories_g: 20, estimated_grams: 15 },
  { name: 'Sweet chilli sauce', portion: '1 tbsp', protein_g: 0.1, calories_g: 40, estimated_grams: 15 },
  { name: 'Relish', portion: '1 tbsp', protein_g: 0.1, calories_g: 20, estimated_grams: 15 },
  { name: 'Jam', portion: '1 tbsp', protein_g: 0.1, calories_g: 50, estimated_grams: 20 },
  { name: 'Marmalade', portion: '1 tbsp', protein_g: 0.1, calories_g: 50, estimated_grams: 20 },
  { name: 'Peanut sauce', portion: '1 tbsp', protein_g: 2, calories_g: 60, estimated_grams: 15 },
  { name: 'Tzatziki', portion: '2 tbsp', protein_g: 1.5, calories_g: 30, estimated_grams: 30 },
  { name: 'Raita', portion: '2 tbsp', protein_g: 1.5, calories_g: 25, estimated_grams: 30 },
  { name: 'Mint chutney', portion: '1 tbsp', protein_g: 0.3, calories_g: 10, estimated_grams: 15 },
  { name: 'Tamarind chutney', portion: '1 tbsp', protein_g: 0.2, calories_g: 30, estimated_grams: 15 },
  { name: 'Pickle (Indian)', portion: '1 tbsp', protein_g: 0.3, calories_g: 40, estimated_grams: 15, aliases: ['achaar'] },

  // —— Indian meals ——
  { name: 'Masala dosa', portion: '1 large', protein_g: 7, calories_g: 250, estimated_grams: 150 },
  { name: 'Rava dosa', portion: '1 large', protein_g: 5, calories_g: 200, estimated_grams: 100 },
  { name: 'Plain dosa', portion: '1 large', protein_g: 5.6, calories_g: 170, estimated_grams: 90 },
  { name: 'Uttapam', portion: '1 uttapam', protein_g: 5, calories_g: 180, estimated_grams: 100 },
  { name: 'Appam', portion: '1 appam', protein_g: 2, calories_g: 120, estimated_grams: 60 },
  { name: 'Puri', portion: '1 puri', protein_g: 2, calories_g: 100, estimated_grams: 30 },
  { name: 'Bhatura', portion: '1 bhatura', protein_g: 5, calories_g: 250, estimated_grams: 80 },
  { name: 'Thepla', portion: '1 thepla', protein_g: 3, calories_g: 120, estimated_grams: 40 },
  { name: 'Khichdi', portion: '1 bowl', protein_g: 8, calories_g: 220, estimated_grams: 250 },
  { name: 'Pulao', portion: '1 plate', protein_g: 6, calories_g: 280, estimated_grams: 220 },
  { name: 'Veg biryani', portion: '1 plate', protein_g: 10, calories_g: 350, estimated_grams: 280 },
  { name: 'Chicken biryani', portion: '1 plate', protein_g: 22, calories_g: 480, estimated_grams: 320 },
  { name: 'Mutton biryani', portion: '1 plate', protein_g: 24, calories_g: 520, estimated_grams: 320 },
  { name: 'Palak paneer', portion: '1 bowl', protein_g: 14, calories_g: 280, estimated_grams: 200 },
  { name: 'Paneer tikka', portion: '1 serving', protein_g: 18, calories_g: 280, estimated_grams: 150 },
  { name: 'Paneer butter masala', portion: '1 bowl', protein_g: 16, calories_g: 350, estimated_grams: 220 },
  { name: 'Aloo gobi', portion: '1 bowl', protein_g: 4, calories_g: 180, estimated_grams: 200 },
  { name: 'Aloo paratha', portion: '1 paratha', protein_g: 6, calories_g: 280, estimated_grams: 120 },
  { name: 'Gobi paratha', portion: '1 paratha', protein_g: 5, calories_g: 250, estimated_grams: 110 },
  { name: 'Chole bhature', portion: '1 plate', protein_g: 15, calories_g: 550, estimated_grams: 350 },
  { name: 'Pav bhaji', portion: '1 plate', protein_g: 10, calories_g: 400, estimated_grams: 300 },
  { name: 'Vada pav', portion: '1 vada pav', protein_g: 6, calories_g: 280, estimated_grams: 150 },
  { name: 'Misal pav', portion: '1 plate', protein_g: 12, calories_g: 350, estimated_grams: 280 },
  { name: 'Dahi vada', portion: '1 serving', protein_g: 8, calories_g: 220, estimated_grams: 150 },
  { name: 'Rasam', portion: '1 bowl', protein_g: 2, calories_g: 50, estimated_grams: 200 },
  { name: 'Rasgulla', portion: '1 piece', protein_g: 1.5, calories_g: 100, estimated_grams: 40 },
  { name: 'Gulab jamun', portion: '1 piece', protein_g: 1.5, calories_g: 150, estimated_grams: 40 },
  { name: 'Jalebi', portion: '1 piece', protein_g: 0.5, calories_g: 80, estimated_grams: 25 },
  { name: 'Ladoo', portion: '1 ladoo', protein_g: 2, calories_g: 120, estimated_grams: 30 },
  { name: 'Halwa', portion: '1 serving', protein_g: 3, calories_g: 250, estimated_grams: 100 },
  { name: 'Kheer', portion: '1 bowl', protein_g: 5, calories_g: 220, estimated_grams: 150 },
  { name: 'Idiyappam', portion: '1 serving', protein_g: 3, calories_g: 150, estimated_grams: 100 },
  { name: 'Puttu', portion: '1 serving', protein_g: 4, calories_g: 180, estimated_grams: 120 },
  { name: 'Medu vada', portion: '1 vada', protein_g: 3, calories_g: 140, estimated_grams: 50 },
  { name: 'Bonda', portion: '1 bonda', protein_g: 3, calories_g: 150, estimated_grams: 50 },
  { name: 'Bhaji', portion: '1 serving', protein_g: 3, calories_g: 180, estimated_grams: 80 },
  { name: 'Kathi roll', portion: '1 roll', protein_g: 15, calories_g: 350, estimated_grams: 200 },
  { name: 'Frankie', portion: '1 frankie', protein_g: 12, calories_g: 320, estimated_grams: 200 },

  // —— Breakfast / bakery ——
  { name: 'French toast', portion: '1 slice', protein_g: 6, calories_g: 180, estimated_grams: 65 },
  { name: 'Crepe', portion: '1 crepe', protein_g: 4, calories_g: 120, estimated_grams: 50 },
  { name: 'Muffin', portion: '1 muffin', protein_g: 4, calories_g: 350, estimated_grams: 100 },
  { name: 'Blueberry muffin', portion: '1 muffin', protein_g: 4, calories_g: 360, estimated_grams: 100 },
  { name: 'Banana bread', portion: '1 slice', protein_g: 3, calories_g: 200, estimated_grams: 60 },
  { name: 'Scone', portion: '1 scone', protein_g: 4, calories_g: 200, estimated_grams: 55 },
  { name: 'Danish pastry', portion: '1 pastry', protein_g: 4, calories_g: 280, estimated_grams: 70 },
  { name: 'Pain au chocolat', portion: '1 pastry', protein_g: 5, calories_g: 300, estimated_grams: 70 },
  { name: 'Donut', portion: '1 donut', protein_g: 3, calories_g: 250, estimated_grams: 60, aliases: ['doughnut'] },
  { name: 'Cinnamon roll', portion: '1 roll', protein_g: 4, calories_g: 320, estimated_grams: 90 },
  { name: 'Granola bar', portion: '1 bar', protein_g: 3, calories_g: 150, estimated_grams: 35 },
  { name: 'Protein bar', portion: '1 bar', protein_g: 20, calories_g: 200, estimated_grams: 60 },
  { name: 'Energy bar', portion: '1 bar', protein_g: 8, calories_g: 200, estimated_grams: 50 },
  { name: 'Rice cake', portion: '1 cake', protein_g: 0.7, calories_g: 35, estimated_grams: 9 },
  { name: 'Crackers', portion: '5 crackers', protein_g: 2, calories_g: 80, estimated_grams: 20 },
  { name: 'Digestive biscuit', portion: '1 biscuit', protein_g: 1, calories_g: 70, estimated_grams: 15 },
  { name: 'Shortbread', portion: '1 biscuit', protein_g: 1, calories_g: 80, estimated_grams: 15 },
  { name: 'Biscuit', portion: '1 biscuit', protein_g: 1, calories_g: 60, estimated_grams: 12 },

  // —— Fast food / meals ——
  { name: 'Cheeseburger', portion: '1 burger', protein_g: 20, calories_g: 450, estimated_grams: 200 },
  { name: 'Double cheeseburger', portion: '1 burger', protein_g: 30, calories_g: 600, estimated_grams: 250 },
  { name: 'Chicken burger', portion: '1 burger', protein_g: 25, calories_g: 480, estimated_grams: 220 },
  { name: 'Veggie wrap', portion: '1 wrap', protein_g: 10, calories_g: 300, estimated_grams: 200 },
  { name: 'Chicken wrap', portion: '1 wrap', protein_g: 25, calories_g: 400, estimated_grams: 220 },
  { name: 'Burrito', portion: '1 burrito', protein_g: 20, calories_g: 500, estimated_grams: 300 },
  { name: 'Burrito bowl', portion: '1 bowl', protein_g: 25, calories_g: 550, estimated_grams: 400 },
  { name: 'Quesadilla', portion: '1 quesadilla', protein_g: 18, calories_g: 450, estimated_grams: 200 },
  { name: 'Nachos', portion: '1 serving', protein_g: 10, calories_g: 400, estimated_grams: 150 },
  { name: 'Pizza margherita', portion: '1 slice', protein_g: 10, calories_g: 250, estimated_grams: 90 },
  { name: 'Pepperoni pizza', portion: '1 slice', protein_g: 12, calories_g: 300, estimated_grams: 100 },
  { name: 'BBQ chicken pizza', portion: '1 slice', protein_g: 14, calories_g: 290, estimated_grams: 100 },
  { name: 'Caesar salad', portion: '1 bowl', protein_g: 15, calories_g: 350, estimated_grams: 250 },
  { name: 'Greek salad', portion: '1 bowl', protein_g: 8, calories_g: 220, estimated_grams: 200 },
  { name: 'Cobb salad', portion: '1 bowl', protein_g: 25, calories_g: 450, estimated_grams: 300 },
  { name: 'Garden salad', portion: '1 bowl', protein_g: 2, calories_g: 50, estimated_grams: 150 },
  { name: 'Chicken salad', portion: '1 bowl', protein_g: 25, calories_g: 300, estimated_grams: 250 },
  { name: 'Tuna salad', portion: '1 serving', protein_g: 20, calories_g: 250, estimated_grams: 150 },
  { name: 'Egg fried rice', portion: '1 plate', protein_g: 12, calories_g: 400, estimated_grams: 280 },
  { name: 'Chicken fried rice', portion: '1 plate', protein_g: 18, calories_g: 450, estimated_grams: 300 },
  { name: 'Pad thai', portion: '1 plate', protein_g: 15, calories_g: 450, estimated_grams: 350 },
  { name: 'Pho', portion: '1 bowl', protein_g: 20, calories_g: 400, estimated_grams: 500 },
  { name: 'Ramen (tonkotsu)', portion: '1 bowl', protein_g: 20, calories_g: 550, estimated_grams: 500 },
  { name: 'Curry rice', portion: '1 plate', protein_g: 12, calories_g: 450, estimated_grams: 350 },
  { name: 'Katsu curry', portion: '1 plate', protein_g: 25, calories_g: 700, estimated_grams: 450 },
  { name: 'Full English breakfast', portion: '1 plate', protein_g: 35, calories_g: 800, estimated_grams: 450 },
  { name: 'Beans on toast', portion: '1 serving', protein_g: 12, calories_g: 300, estimated_grams: 250 },
  { name: 'Avocado toast', portion: '1 serving', protein_g: 8, calories_g: 280, estimated_grams: 150 },
  { name: 'Bagel with cream cheese', portion: '1 bagel', protein_g: 12, calories_g: 350, estimated_grams: 140 },
  { name: 'Club sandwich', portion: '1 sandwich', protein_g: 25, calories_g: 500, estimated_grams: 250 },
  { name: 'BLT', portion: '1 sandwich', protein_g: 15, calories_g: 400, estimated_grams: 200 },
  { name: 'Grilled cheese', portion: '1 sandwich', protein_g: 12, calories_g: 400, estimated_grams: 150 },
  { name: 'Toastie', portion: '1 toastie', protein_g: 14, calories_g: 380, estimated_grams: 160 },
  { name: 'Soup of the day', portion: '1 bowl', protein_g: 5, calories_g: 120, estimated_grams: 250 },
  { name: 'Tomato soup', portion: '1 bowl', protein_g: 3, calories_g: 100, estimated_grams: 250 },
  { name: 'Chicken soup', portion: '1 bowl', protein_g: 10, calories_g: 120, estimated_grams: 250 },
  { name: 'Mushroom soup', portion: '1 bowl', protein_g: 4, calories_g: 140, estimated_grams: 250 },
  { name: 'Lentil soup', portion: '1 bowl', protein_g: 10, calories_g: 180, estimated_grams: 250 },

  // —— Drinks ——
  { name: 'Black coffee', portion: '1 cup', protein_g: 0.3, calories_g: 2, estimated_grams: 240 },
  { name: 'Espresso', portion: '1 shot', protein_g: 0.1, calories_g: 3, estimated_grams: 30 },
  { name: 'Americano', portion: '1 cup', protein_g: 0.3, calories_g: 5, estimated_grams: 240 },
  { name: 'Latte', portion: '1 cup', protein_g: 8, calories_g: 150, estimated_grams: 300 },
  { name: 'Cappuccino', portion: '1 cup', protein_g: 6, calories_g: 120, estimated_grams: 240 },
  { name: 'Flat white', portion: '1 cup', protein_g: 7, calories_g: 140, estimated_grams: 240 },
  { name: 'Cortado', portion: '1 cup', protein_g: 4, calories_g: 80, estimated_grams: 120 },
  { name: 'Mocha', portion: '1 cup', protein_g: 8, calories_g: 250, estimated_grams: 300 },
  { name: 'Iced coffee', portion: '1 cup', protein_g: 1, calories_g: 50, estimated_grams: 300 },
  { name: 'Iced latte', portion: '1 cup', protein_g: 8, calories_g: 140, estimated_grams: 300 },
  { name: 'Matcha latte', portion: '1 cup', protein_g: 6, calories_g: 160, estimated_grams: 300 },
  { name: 'Chai latte', portion: '1 cup', protein_g: 5, calories_g: 180, estimated_grams: 300 },
  { name: 'Masala chai', portion: '1 cup', protein_g: 3, calories_g: 80, estimated_grams: 200 },
  { name: 'Green tea', portion: '1 cup', protein_g: 0, calories_g: 2, estimated_grams: 240 },
  { name: 'Black tea', portion: '1 cup', protein_g: 0, calories_g: 2, estimated_grams: 240 },
  { name: 'Herbal tea', portion: '1 cup', protein_g: 0, calories_g: 2, estimated_grams: 240 },
  { name: 'Apple juice', portion: '1 cup', protein_g: 0.2, calories_g: 110, estimated_grams: 248 },
  { name: 'Grape juice', portion: '1 cup', protein_g: 1, calories_g: 150, estimated_grams: 250 },
  { name: 'Cranberry juice', portion: '1 cup', protein_g: 0.5, calories_g: 120, estimated_grams: 250 },
  { name: 'Pineapple juice', portion: '1 cup', protein_g: 0.8, calories_g: 130, estimated_grams: 250 },
  { name: 'Mango juice', portion: '1 cup', protein_g: 0.5, calories_g: 140, estimated_grams: 250 },
  { name: 'Lemonade', portion: '1 glass', protein_g: 0, calories_g: 100, estimated_grams: 300 },
  { name: 'Iced tea', portion: '1 glass', protein_g: 0, calories_g: 70, estimated_grams: 300 },
  { name: 'Energy drink', portion: '1 can', protein_g: 0, calories_g: 110, estimated_grams: 250 },
  { name: 'Sports drink', portion: '1 bottle', protein_g: 0, calories_g: 80, estimated_grams: 500 },
  { name: 'Coconut water', portion: '1 glass', protein_g: 1.7, calories_g: 45, estimated_grams: 240 },
  { name: 'Sparkling water', portion: '1 glass', protein_g: 0, calories_g: 0, estimated_grams: 250 },
  { name: 'Diet soda', portion: '1 can', protein_g: 0, calories_g: 1, estimated_grams: 355 },
  { name: 'Kombucha', portion: '1 bottle', protein_g: 0, calories_g: 30, estimated_grams: 250 },
  { name: 'Protein water', portion: '1 bottle', protein_g: 20, calories_g: 80, estimated_grams: 500 },
  { name: 'Casein protein', portion: '1 scoop', protein_g: 24, calories_g: 120, estimated_grams: 30 },
  { name: 'Plant protein powder', portion: '1 scoop', protein_g: 20, calories_g: 110, estimated_grams: 30 },
  { name: 'Mass gainer', portion: '1 scoop', protein_g: 25, calories_g: 400, estimated_grams: 80 },
  { name: 'Creatine', portion: '1 scoop', protein_g: 0, calories_g: 0, estimated_grams: 5 },
  { name: 'BCAA drink', portion: '1 serving', protein_g: 5, calories_g: 20, estimated_grams: 300 },
  { name: 'Meal replacement shake', portion: '1 shake', protein_g: 25, calories_g: 220, estimated_grams: 330 },

  // —— Snacks / sweets ——
  { name: 'Popcorn', portion: '1 bowl', protein_g: 3, calories_g: 120, estimated_grams: 30 },
  { name: 'Pretzels', portion: '1 handful', protein_g: 3, calories_g: 110, estimated_grams: 30 },
  { name: 'Tortilla chips', portion: '1 handful', protein_g: 2, calories_g: 140, estimated_grams: 28 },
  { name: 'Doritos', portion: '1 handful', protein_g: 2, calories_g: 150, estimated_grams: 30 },
  { name: 'Pringles', portion: '1 serving', protein_g: 1.5, calories_g: 150, estimated_grams: 30 },
  {
    name: 'Dark chocolate',
    portion: '2 squares',
    protein_g: 1.5,
    calories_g: 110,
    estimated_grams: 20,
    aliases: ['dark choc', 'plain chocolate', '70% chocolate'],
  },
  {
    name: 'Milk chocolate',
    portion: '2 squares',
    protein_g: 1.5,
    calories_g: 120,
    estimated_grams: 20,
    aliases: ['milk choc', 'milky chocolate'],
  },
  {
    name: 'White chocolate',
    portion: '2 squares',
    protein_g: 1,
    calories_g: 130,
    estimated_grams: 20,
    aliases: ['white choc'],
  },
  { name: 'Brownie', portion: '1 brownie', protein_g: 3, calories_g: 250, estimated_grams: 60 },
  { name: 'Cheesecake', portion: '1 slice', protein_g: 6, calories_g: 350, estimated_grams: 100 },
  { name: 'Tiramisu', portion: '1 slice', protein_g: 5, calories_g: 300, estimated_grams: 90 },
  { name: 'Pudding', portion: '1 serving', protein_g: 3, calories_g: 150, estimated_grams: 120 },
  { name: 'Jelly', portion: '1 serving', protein_g: 1, calories_g: 70, estimated_grams: 100 },
  { name: 'Marshmallow', portion: '1 marshmallow', protein_g: 0.1, calories_g: 25, estimated_grams: 7 },
  { name: 'Candy', portion: '1 serving', protein_g: 0, calories_g: 100, estimated_grams: 25 },
  { name: 'Gummy bears', portion: '1 handful', protein_g: 1, calories_g: 90, estimated_grams: 30 },
  { name: 'Protein cookies', portion: '1 cookie', protein_g: 10, calories_g: 180, estimated_grams: 50 },
  { name: 'Rice pudding', portion: '1 bowl', protein_g: 5, calories_g: 200, estimated_grams: 150 },
  { name: 'Yogurt parfait', portion: '1 serving', protein_g: 10, calories_g: 220, estimated_grams: 200 },
  { name: 'Acai bowl', portion: '1 bowl', protein_g: 5, calories_g: 280, estimated_grams: 300 },

  // —— Chocolate bars / cocoa / sweets ——
  {
    name: 'Chocolate bar',
    portion: '1 bar',
    protein_g: 3,
    calories_g: 230,
    estimated_grams: 45,
    aliases: ['choc bar', 'candy bar', 'chocolate'],
  },
  {
    name: 'Milk chocolate bar',
    portion: '1 bar',
    protein_g: 3.5,
    calories_g: 240,
    estimated_grams: 45,
    aliases: ['milk chocolate', 'milk choc bar', 'milky chocolate bar', 'dairy milk bar'],
  },
  {
    name: 'Dark chocolate bar',
    portion: '1 bar',
    protein_g: 3,
    calories_g: 220,
    estimated_grams: 45,
    aliases: ['dark chocolate', 'dark choc bar', 'plain chocolate bar'],
  },
  {
    name: 'White chocolate bar',
    portion: '1 bar',
    protein_g: 2.5,
    calories_g: 250,
    estimated_grams: 45,
    aliases: ['white chocolate', 'white choc bar'],
  },
  {
    name: 'Cadbury Dairy Milk',
    portion: '1 bar',
    protein_g: 3.5,
    calories_g: 240,
    estimated_grams: 45,
    aliases: ['dairy milk', 'cadbury', 'cadburys'],
  },
  { name: 'Galaxy bar', portion: '1 bar', protein_g: 3, calories_g: 230, estimated_grams: 42, aliases: ['galaxy chocolate'] },
  { name: 'KitKat', portion: '1 bar', protein_g: 2.5, calories_g: 210, estimated_grams: 42, aliases: ['kit kat', 'kitkat bar'] },
  { name: 'Snickers', portion: '1 bar', protein_g: 4.5, calories_g: 250, estimated_grams: 50, aliases: ['snickers bar'] },
  { name: 'Twix', portion: '1 bar', protein_g: 2.5, calories_g: 250, estimated_grams: 50, aliases: ['twix bar'] },
  { name: 'Mars bar', portion: '1 bar', protein_g: 2.5, calories_g: 230, estimated_grams: 51, aliases: ['mars'] },
  { name: 'Bounty', portion: '1 bar', protein_g: 2, calories_g: 240, estimated_grams: 57, aliases: ['bounty bar', 'coconut chocolate bar'] },
  { name: 'Maltesers', portion: '1 handful', protein_g: 2, calories_g: 150, estimated_grams: 30, aliases: ['malteser'] },
  { name: 'Smarties', portion: '1 handful', protein_g: 1.5, calories_g: 140, estimated_grams: 30 },
  { name: 'M&Ms', portion: '1 handful', protein_g: 2, calories_g: 150, estimated_grams: 30, aliases: ['m and ms', 'mms'] },
  { name: "Reese's Peanut Butter Cups", portion: '2 cups', protein_g: 5, calories_g: 210, estimated_grams: 42, aliases: ['reeses', 'peanut butter cups', 'reese'] },
  { name: 'Ferrero Rocher', portion: '1 piece', protein_g: 1.5, calories_g: 75, estimated_grams: 13 },
  { name: 'Toblerone', portion: '2 triangles', protein_g: 2, calories_g: 140, estimated_grams: 25 },
  { name: 'Chocolate coins', portion: '1 handful', protein_g: 1, calories_g: 120, estimated_grams: 25 },
  { name: 'Chocolate chips', portion: '1 tbsp', protein_g: 0.5, calories_g: 70, estimated_grams: 15, aliases: ['choc chips', 'baking chocolate chips'] },
  {
    name: 'Cocoa powder',
    portion: '1 tbsp',
    protein_g: 1,
    calories_g: 12,
    estimated_grams: 5,
    aliases: ['cocoa', 'unsweetened cocoa', 'cacao powder', 'cacao'],
  },
  {
    name: 'Drinking chocolate powder',
    portion: '2 tbsp',
    protein_g: 1.5,
    calories_g: 80,
    estimated_grams: 20,
    aliases: ['hot chocolate powder', 'cocoa mix', 'instant hot chocolate'],
  },
  {
    name: 'Chocolate syrup',
    portion: '2 tbsp',
    protein_g: 0.5,
    calories_g: 100,
    estimated_grams: 40,
    aliases: ['choc syrup', 'chocolate sauce', 'hershey syrup'],
  },
  { name: 'Chocolate spread', portion: '1 tbsp', protein_g: 1, calories_g: 90, estimated_grams: 15, aliases: ['choc spread'] },
  { name: 'Nutella', portion: '1 tbsp', protein_g: 1, calories_g: 100, estimated_grams: 15, aliases: ['hazelnut chocolate spread', 'nutella spread'] },
  { name: 'Chocolate pudding', portion: '1 serving', protein_g: 4, calories_g: 160, estimated_grams: 120, aliases: ['choc pudding'] },
  { name: 'Chocolate mousse', portion: '1 serving', protein_g: 4, calories_g: 200, estimated_grams: 90 },
  { name: 'Chocolate cake', portion: '1 slice', protein_g: 4, calories_g: 350, estimated_grams: 90, aliases: ['choc cake'] },
  { name: 'Chocolate muffin', portion: '1 muffin', protein_g: 4, calories_g: 320, estimated_grams: 90, aliases: ['choc muffin'] },
  { name: 'Chocolate chip cookie', portion: '1 cookie', protein_g: 2, calories_g: 140, estimated_grams: 30, aliases: ['choc chip cookie', 'chocolate cookie'] },
  { name: 'Chocolate croissant', portion: '1 pastry', protein_g: 5, calories_g: 300, estimated_grams: 70, aliases: ['choc croissant'] },
  { name: 'Chocolate milkshake', portion: '1 glass', protein_g: 9, calories_g: 380, estimated_grams: 300, aliases: ['choc milkshake', 'chocolate shake'] },
  { name: 'Iced chocolate', portion: '1 glass', protein_g: 7, calories_g: 250, estimated_grams: 300, aliases: ['iced hot chocolate', 'frozen hot chocolate'] },
  { name: 'Mocha', portion: '1 cup', protein_g: 6, calories_g: 200, estimated_grams: 240, aliases: ['cafe mocha', 'mocha latte'] },
  { name: 'White hot chocolate', portion: '1 cup', protein_g: 7, calories_g: 280, estimated_grams: 250 },
  { name: 'Oreo', portion: '2 cookies', protein_g: 1.5, calories_g: 110, estimated_grams: 22, aliases: ['oreos', 'oreo cookies'] },
  { name: 'Digestive biscuit', portion: '1 biscuit', protein_g: 1.2, calories_g: 70, estimated_grams: 15, aliases: ['digestives'] },
  { name: 'Bourbon biscuit', portion: '1 biscuit', protein_g: 1, calories_g: 70, estimated_grams: 15, aliases: ['bourbons'] },
  { name: 'Custard cream', portion: '1 biscuit', protein_g: 0.8, calories_g: 60, estimated_grams: 12 },
  { name: 'Jaffa cake', portion: '1 cake', protein_g: 0.5, calories_g: 46, estimated_grams: 12 },
  { name: 'Fudge', portion: '1 piece', protein_g: 0.5, calories_g: 90, estimated_grams: 20 },
  { name: 'Toffee', portion: '1 piece', protein_g: 0.2, calories_g: 60, estimated_grams: 12, aliases: ['caramel toffee'] },
  { name: 'Caramel', portion: '1 tbsp', protein_g: 0.2, calories_g: 60, estimated_grams: 20, aliases: ['caramel sauce'] },
  { name: 'Dulce de leche', portion: '1 tbsp', protein_g: 1, calories_g: 60, estimated_grams: 20 },
  { name: 'Eclair', portion: '1 eclair', protein_g: 4, calories_g: 260, estimated_grams: 70, aliases: ['chocolate eclair'] },
  { name: 'Profiterole', portion: '1 piece', protein_g: 2, calories_g: 90, estimated_grams: 30 },
  { name: 'Fruit and nut bar', portion: '1 bar', protein_g: 4, calories_g: 180, estimated_grams: 40, aliases: ['fruit & nut', 'fruit n nut'] },
  { name: 'Flapjack', portion: '1 slice', protein_g: 3, calories_g: 250, estimated_grams: 60, aliases: ['oat bar'] },
  { name: 'Cereal bar', portion: '1 bar', protein_g: 2, calories_g: 130, estimated_grams: 30, aliases: ['granola bar snack'] },

  // —— Spreads / sweeteners / condiments ——
  { name: 'Maple syrup', portion: '1 tbsp', protein_g: 0, calories_g: 52, estimated_grams: 20 },
  { name: 'Golden syrup', portion: '1 tbsp', protein_g: 0, calories_g: 60, estimated_grams: 20 },
  { name: 'Agave syrup', portion: '1 tbsp', protein_g: 0, calories_g: 60, estimated_grams: 21, aliases: ['agave'] },
  { name: 'Marmalade', portion: '1 tbsp', protein_g: 0.1, calories_g: 50, estimated_grams: 20 },
  { name: 'Cashew butter', portion: '1 tbsp', protein_g: 3, calories_g: 94, estimated_grams: 16 },
  { name: 'Sunflower seed butter', portion: '1 tbsp', protein_g: 3, calories_g: 90, estimated_grams: 16 },
  { name: 'Vinegar', portion: '1 tbsp', protein_g: 0, calories_g: 3, estimated_grams: 15 },
  { name: 'Balsamic vinegar', portion: '1 tbsp', protein_g: 0.1, calories_g: 14, estimated_grams: 16 },
  { name: 'Apple cider vinegar', portion: '1 tbsp', protein_g: 0, calories_g: 3, estimated_grams: 15, aliases: ['acv'] },
  { name: 'Mustard', portion: '1 tsp', protein_g: 0.3, calories_g: 5, estimated_grams: 5 },
  { name: 'Dijon mustard', portion: '1 tsp', protein_g: 0.3, calories_g: 5, estimated_grams: 5 },
  { name: 'BBQ sauce', portion: '2 tbsp', protein_g: 0.3, calories_g: 60, estimated_grams: 35, aliases: ['barbecue sauce'] },
  { name: 'Hot sauce', portion: '1 tsp', protein_g: 0.1, calories_g: 2, estimated_grams: 5 },
  { name: 'Sriracha', portion: '1 tsp', protein_g: 0.2, calories_g: 5, estimated_grams: 6 },
  { name: 'Pesto', portion: '1 tbsp', protein_g: 1.5, calories_g: 80, estimated_grams: 15 },
  { name: 'Tomato paste', portion: '1 tbsp', protein_g: 0.8, calories_g: 13, estimated_grams: 16, aliases: ['tomato puree'] },
  { name: 'Passata', portion: '0.5 cup', protein_g: 1.5, calories_g: 35, estimated_grams: 120 },
  { name: 'Stock cube', portion: '1 cube', protein_g: 1, calories_g: 10, estimated_grams: 10, aliases: ['bouillon cube'] },
  { name: 'Gravy', portion: '0.25 cup', protein_g: 1, calories_g: 30, estimated_grams: 60 },

  // —— Breakfast / cereal ——
  { name: 'Cheerios', portion: '1 bowl', protein_g: 3, calories_g: 110, estimated_grams: 30 },
  { name: 'Weetabix', portion: '2 biscuits', protein_g: 4.5, calories_g: 135, estimated_grams: 37 },
  { name: 'Shredded Wheat', portion: '2 biscuits', protein_g: 4, calories_g: 140, estimated_grams: 45 },
  { name: 'Cornflakes', portion: '1 bowl', protein_g: 2, calories_g: 110, estimated_grams: 30, aliases: ['corn flakes'] },
  { name: 'Rice Krispies', portion: '1 bowl', protein_g: 1.5, calories_g: 110, estimated_grams: 30 },
  { name: 'Coco Pops', portion: '1 bowl', protein_g: 2, calories_g: 120, estimated_grams: 30, aliases: ['cocoa pops', 'chocolate cereal'] },
  { name: 'Overnight oats', portion: '1 serving', protein_g: 10, calories_g: 280, estimated_grams: 250 },
  { name: 'Chia pudding', portion: '1 serving', protein_g: 6, calories_g: 200, estimated_grams: 180 },
  { name: 'Crumpet', portion: '1 crumpet', protein_g: 3, calories_g: 90, estimated_grams: 40 },
  { name: 'English muffin', portion: '1 muffin', protein_g: 5, calories_g: 130, estimated_grams: 57 },
  { name: 'Scone', portion: '1 scone', protein_g: 4, calories_g: 200, estimated_grams: 60 },
  { name: 'French toast', portion: '1 slice', protein_g: 6, calories_g: 180, estimated_grams: 70, aliases: ['eggy bread'] },
  { name: 'Waffle', portion: '1 waffle', protein_g: 5, calories_g: 220, estimated_grams: 75 },
  { name: 'Pancake', portion: '1 pancake', protein_g: 4, calories_g: 120, estimated_grams: 50 },

  // —— UK / cafe / takeaway ——
  { name: 'Flat white', portion: '1 cup', protein_g: 6, calories_g: 120, estimated_grams: 200 },
  { name: 'Cappuccino', portion: '1 cup', protein_g: 6, calories_g: 120, estimated_grams: 200 },
  { name: 'Latte', portion: '1 cup', protein_g: 8, calories_g: 150, estimated_grams: 240 },
  { name: 'Americano', portion: '1 cup', protein_g: 0.5, calories_g: 10, estimated_grams: 240 },
  { name: 'Espresso', portion: '1 shot', protein_g: 0.2, calories_g: 3, estimated_grams: 30 },
  { name: 'Matcha latte', portion: '1 cup', protein_g: 5, calories_g: 160, estimated_grams: 240 },
  { name: 'Chai latte', portion: '1 cup', protein_g: 5, calories_g: 180, estimated_grams: 240 },
  { name: 'Iced coffee', portion: '1 glass', protein_g: 2, calories_g: 80, estimated_grams: 300 },
  { name: 'Bubble tea', portion: '1 cup', protein_g: 1, calories_g: 250, estimated_grams: 400, aliases: ['boba', 'boba tea'] },
  { name: 'Banana milkshake', portion: '1 glass', protein_g: 8, calories_g: 320, estimated_grams: 300 },
  { name: 'Strawberry milkshake', portion: '1 glass', protein_g: 8, calories_g: 300, estimated_grams: 300 },
  { name: 'Jacket potato', portion: '1 potato', protein_g: 7, calories_g: 250, estimated_grams: 300, aliases: ['baked potato'] },
  { name: 'Mash', portion: '1 scoop', protein_g: 3, calories_g: 150, estimated_grams: 150, aliases: ['mashed potato', 'mashed potatoes'] },
  { name: 'Chips', portion: '1 serving', protein_g: 4, calories_g: 350, estimated_grams: 150, aliases: ['fries', 'french fries', 'chip shop chips'] },
  { name: 'Onion rings', portion: '1 serving', protein_g: 3, calories_g: 280, estimated_grams: 80 },
  { name: 'Garlic bread', portion: '1 slice', protein_g: 3, calories_g: 150, estimated_grams: 40 },
  { name: 'Sausage roll', portion: '1 roll', protein_g: 8, calories_g: 300, estimated_grams: 100 },
  { name: 'Cornish pasty', portion: '1 pasty', protein_g: 14, calories_g: 450, estimated_grams: 200, aliases: ['pasty'] },
  { name: 'Quiche', portion: '1 slice', protein_g: 10, calories_g: 300, estimated_grams: 120 },
  { name: 'Scotch egg', portion: '1 egg', protein_g: 14, calories_g: 300, estimated_grams: 120 },
  { name: 'Prawn cocktail', portion: '1 serving', protein_g: 12, calories_g: 180, estimated_grams: 120 },
  { name: 'Beans on toast', portion: '1 serving', protein_g: 12, calories_g: 320, estimated_grams: 250 },
  { name: 'Baked beans', portion: '0.5 can', protein_g: 10, calories_g: 180, estimated_grams: 200, aliases: ['heinz beans', 'tinned beans'] },
  { name: 'Tinned tuna', portion: '1 can drained', protein_g: 25, calories_g: 120, estimated_grams: 100, aliases: ['canned tuna'] },
  { name: 'Tinned salmon', portion: '1 serving', protein_g: 20, calories_g: 150, estimated_grams: 100, aliases: ['canned salmon'] },
  { name: 'Sardines', portion: '1 tin', protein_g: 18, calories_g: 180, estimated_grams: 90 },
  { name: 'Anchovies', portion: '4 fillets', protein_g: 5, calories_g: 40, estimated_grams: 20 },
  { name: 'Smoked salmon', portion: '1 serving', protein_g: 16, calories_g: 120, estimated_grams: 70 },
  { name: 'Bagel', portion: '1 bagel', protein_g: 10, calories_g: 270, estimated_grams: 95 },
  { name: 'Ciabatta', portion: '1 roll', protein_g: 8, calories_g: 250, estimated_grams: 90 },
  { name: 'Pizza slice', portion: '1 slice', protein_g: 12, calories_g: 285, estimated_grams: 100 },
  { name: 'Burrito', portion: '1 burrito', protein_g: 20, calories_g: 500, estimated_grams: 350 },
  { name: 'Taco', portion: '1 taco', protein_g: 10, calories_g: 200, estimated_grams: 100 },
  { name: 'Quesadilla', portion: '1 quesadilla', protein_g: 18, calories_g: 450, estimated_grams: 200 },
  { name: 'Nachos', portion: '1 serving', protein_g: 12, calories_g: 450, estimated_grams: 200 },
  { name: 'Falafel', portion: '3 pieces', protein_g: 8, calories_g: 250, estimated_grams: 90 },
  { name: 'Kebab', portion: '1 serving', protein_g: 25, calories_g: 500, estimated_grams: 300, aliases: ['doner kebab', 'shawarma'] },
  { name: 'Shawarma wrap', portion: '1 wrap', protein_g: 22, calories_g: 480, estimated_grams: 280 },

  // —— Indian extras ——
  { name: 'Butter chicken', portion: '1 bowl', protein_g: 28, calories_g: 420, estimated_grams: 250, aliases: ['murgh makhani'] },
  { name: 'Chicken tikka masala', portion: '1 bowl', protein_g: 26, calories_g: 400, estimated_grams: 250, aliases: ['tikka masala'] },
  { name: 'Korma', portion: '1 bowl', protein_g: 20, calories_g: 380, estimated_grams: 250 },
  { name: 'Vindaloo', portion: '1 bowl', protein_g: 24, calories_g: 350, estimated_grams: 250 },
  { name: 'Saag paneer', portion: '1 bowl', protein_g: 16, calories_g: 320, estimated_grams: 220, aliases: ['palak paneer'] },
  { name: 'Aloo gobi', portion: '1 bowl', protein_g: 5, calories_g: 180, estimated_grams: 200 },
  { name: 'Dal makhani', portion: '1 bowl', protein_g: 12, calories_g: 280, estimated_grams: 220 },
  { name: 'Chana masala', portion: '1 bowl', protein_g: 10, calories_g: 220, estimated_grams: 200, aliases: ['chole masala'] },
  { name: 'Raita', portion: '2 tbsp', protein_g: 2, calories_g: 40, estimated_grams: 40 },
  { name: 'Papad', portion: '1 papad', protein_g: 2, calories_g: 40, estimated_grams: 10, aliases: ['papadum', 'poppadom'] },
  { name: 'Achaar', portion: '1 tbsp', protein_g: 0.2, calories_g: 25, estimated_grams: 15, aliases: ['indian pickle', 'mango pickle'] },
  { name: 'Samosa', portion: '1 samosa', protein_g: 4, calories_g: 180, estimated_grams: 60 },
  { name: 'Pakora', portion: '1 serving', protein_g: 4, calories_g: 200, estimated_grams: 60, aliases: ['bhaji', 'onion bhaji'] },
  { name: 'Vada', portion: '1 vada', protein_g: 3, calories_g: 120, estimated_grams: 40, aliases: ['medu vada'] },
  { name: 'Uttapam', portion: '1 uttapam', protein_g: 5, calories_g: 180, estimated_grams: 90 },
  { name: 'Appam', portion: '1 appam', protein_g: 2, calories_g: 120, estimated_grams: 60 },
  { name: 'Pongal', portion: '1 serving', protein_g: 6, calories_g: 250, estimated_grams: 200 },
  { name: 'Khichdi', portion: '1 bowl', protein_g: 8, calories_g: 220, estimated_grams: 220, aliases: ['khichri'] },
  { name: 'Pulao', portion: '1 plate', protein_g: 6, calories_g: 280, estimated_grams: 200, aliases: ['pilaf', 'pilau'] },
  { name: 'Lemon rice', portion: '1 serving', protein_g: 4, calories_g: 220, estimated_grams: 180 },
  { name: 'Curd rice', portion: '1 bowl', protein_g: 6, calories_g: 200, estimated_grams: 200, aliases: ['thayir sadam'] },
  { name: 'Thepla', portion: '1 thepla', protein_g: 3, calories_g: 110, estimated_grams: 40 },
  { name: 'Dhokla', portion: '2 pieces', protein_g: 4, calories_g: 120, estimated_grams: 60 },
  { name: 'Khandvi', portion: '1 serving', protein_g: 4, calories_g: 140, estimated_grams: 80 },
  { name: 'Sev', portion: '1 handful', protein_g: 2, calories_g: 120, estimated_grams: 25 },
  { name: 'Chaat', portion: '1 serving', protein_g: 5, calories_g: 220, estimated_grams: 150 },
  { name: 'Pani puri', portion: '6 pieces', protein_g: 3, calories_g: 180, estimated_grams: 120, aliases: ['golgappa', 'puchka'] },
  { name: 'Bhel puri', portion: '1 serving', protein_g: 4, calories_g: 200, estimated_grams: 120 },
  { name: 'Gulab jamun', portion: '2 pieces', protein_g: 3, calories_g: 280, estimated_grams: 70 },
  { name: 'Rasgulla', portion: '2 pieces', protein_g: 4, calories_g: 180, estimated_grams: 70 },
  { name: 'Jalebi', portion: '2 pieces', protein_g: 1, calories_g: 200, estimated_grams: 50 },
  { name: 'Ladoo', portion: '1 ladoo', protein_g: 3, calories_g: 180, estimated_grams: 40, aliases: ['laddu'] },
  { name: 'Kheer', portion: '1 bowl', protein_g: 6, calories_g: 220, estimated_grams: 180, aliases: ['rice kheer'] },
  { name: 'Halwa', portion: '1 serving', protein_g: 3, calories_g: 280, estimated_grams: 100 },
  { name: 'Barfi', portion: '1 piece', protein_g: 3, calories_g: 150, estimated_grams: 30, aliases: ['burfi'] },
  { name: 'Kulfi', portion: '1 kulfi', protein_g: 5, calories_g: 200, estimated_grams: 80 },
  { name: 'Falooda', portion: '1 glass', protein_g: 6, calories_g: 300, estimated_grams: 300 },
  { name: 'Mishti doi', portion: '1 pot', protein_g: 5, calories_g: 160, estimated_grams: 120 },
  { name: 'Shrikhand', portion: '1 serving', protein_g: 6, calories_g: 220, estimated_grams: 120 },
  { name: 'Garlic naan', portion: '1 naan', protein_g: 9, calories_g: 290, estimated_grams: 100 },
  { name: 'Butter naan', portion: '1 naan', protein_g: 9, calories_g: 310, estimated_grams: 100 },

  // —— Pasta / Asian / grains ——
  { name: 'Spaghetti', portion: '1 serving cooked', protein_g: 7, calories_g: 220, estimated_grams: 140 },
  { name: 'Penne', portion: '1 serving cooked', protein_g: 7, calories_g: 220, estimated_grams: 140 },
  { name: 'Mac and cheese', portion: '1 bowl', protein_g: 12, calories_g: 400, estimated_grams: 250, aliases: ['macaroni cheese', 'macaroni and cheese'] },
  { name: 'Carbonara', portion: '1 plate', protein_g: 18, calories_g: 450, estimated_grams: 300 },
  { name: 'Bolognese', portion: '1 plate', protein_g: 22, calories_g: 420, estimated_grams: 300, aliases: ['spaghetti bolognese', 'ragu'] },
  { name: 'Pesto pasta', portion: '1 plate', protein_g: 12, calories_g: 400, estimated_grams: 280 },
  { name: 'Lasagna', portion: '1 serving', protein_g: 20, calories_g: 420, estimated_grams: 280, aliases: ['lasagne'] },
  { name: 'Ravioli', portion: '1 serving', protein_g: 12, calories_g: 280, estimated_grams: 180 },
  { name: 'Gnocchi', portion: '1 serving', protein_g: 6, calories_g: 250, estimated_grams: 180 },
  { name: 'Risotto', portion: '1 bowl', protein_g: 8, calories_g: 350, estimated_grams: 250 },
  { name: 'Couscous', portion: '1 serving', protein_g: 6, calories_g: 180, estimated_grams: 150 },
  { name: 'Bulgur', portion: '1 serving', protein_g: 5, calories_g: 150, estimated_grams: 140 },
  { name: 'Polenta', portion: '1 serving', protein_g: 3, calories_g: 140, estimated_grams: 150 },
  { name: 'Pad Thai', portion: '1 plate', protein_g: 16, calories_g: 450, estimated_grams: 350 },
  { name: 'Chow mein', portion: '1 plate', protein_g: 14, calories_g: 400, estimated_grams: 300 },
  { name: 'Fried noodles', portion: '1 plate', protein_g: 12, calories_g: 420, estimated_grams: 300 },
  { name: 'Stir fry', portion: '1 plate', protein_g: 18, calories_g: 350, estimated_grams: 300, aliases: ['stir-fry'] },
  { name: 'Spring roll', portion: '1 roll', protein_g: 3, calories_g: 120, estimated_grams: 50 },
  { name: 'Egg roll', portion: '1 roll', protein_g: 4, calories_g: 150, estimated_grams: 60 },
  { name: 'Wonton', portion: '4 pieces', protein_g: 8, calories_g: 180, estimated_grams: 80, aliases: ['wontons'] },
  { name: 'Bao bun', portion: '1 bao', protein_g: 8, calories_g: 220, estimated_grams: 90, aliases: ['bao', 'pork bun'] },
  { name: 'Gyoza', portion: '4 pieces', protein_g: 8, calories_g: 200, estimated_grams: 80, aliases: ['potstickers'] },
  { name: 'Edamame', portion: '1 serving', protein_g: 11, calories_g: 120, estimated_grams: 100 },
  { name: 'Seaweed salad', portion: '1 serving', protein_g: 1, calories_g: 70, estimated_grams: 80, aliases: ['seaweed', 'wakame'] },
  { name: 'Nori', portion: '1 sheet', protein_g: 1, calories_g: 10, estimated_grams: 3 },
  { name: 'Miso soup', portion: '1 bowl', protein_g: 3, calories_g: 40, estimated_grams: 240 },
  { name: 'Kimchi', portion: '0.5 cup', protein_g: 1, calories_g: 25, estimated_grams: 75 },
  { name: 'Teriyaki chicken', portion: '1 serving', protein_g: 28, calories_g: 320, estimated_grams: 180 },
  { name: 'Karaage', portion: '1 serving', protein_g: 20, calories_g: 350, estimated_grams: 150, aliases: ['japanese fried chicken'] },
  { name: 'Bibimbap', portion: '1 bowl', protein_g: 20, calories_g: 450, estimated_grams: 400 },
  { name: 'Bulgogi', portion: '1 serving', protein_g: 25, calories_g: 350, estimated_grams: 180 },
  { name: 'Pho', portion: '1 bowl', protein_g: 20, calories_g: 350, estimated_grams: 500 },
  { name: 'Banh mi', portion: '1 sandwich', protein_g: 18, calories_g: 400, estimated_grams: 220 },

  // —— Veg / herbs / pantry staples ——
  { name: 'Courgette', portion: '1 courgette', protein_g: 2, calories_g: 33, estimated_grams: 200, aliases: ['zucchini'] },
  { name: 'Aubergine', portion: '0.5 aubergine', protein_g: 1.5, calories_g: 60, estimated_grams: 200, aliases: ['eggplant'] },
  { name: 'Bell pepper', portion: '1 pepper', protein_g: 1, calories_g: 30, estimated_grams: 120, aliases: ['capsicum', 'sweet pepper'] },
  { name: 'Cauliflower', portion: '1 serving', protein_g: 2, calories_g: 25, estimated_grams: 100 },
  { name: 'Cabbage', portion: '1 serving', protein_g: 1.5, calories_g: 25, estimated_grams: 100 },
  { name: 'Brussels sprouts', portion: '1 serving', protein_g: 3.5, calories_g: 45, estimated_grams: 100 },
  { name: 'Asparagus', portion: '1 serving', protein_g: 2.5, calories_g: 25, estimated_grams: 100 },
  { name: 'Green beans', portion: '1 serving', protein_g: 2, calories_g: 35, estimated_grams: 100, aliases: ['runner beans'] },
  { name: 'Beetroot', portion: '1 beet', protein_g: 1.5, calories_g: 40, estimated_grams: 80, aliases: ['beet'] },
  { name: 'Radish', portion: '4 radishes', protein_g: 0.4, calories_g: 8, estimated_grams: 40 },
  { name: 'Celery', portion: '2 sticks', protein_g: 0.5, calories_g: 10, estimated_grams: 80 },
  { name: 'Leek', portion: '1 leek', protein_g: 1.5, calories_g: 50, estimated_grams: 90 },
  { name: 'Spring onion', portion: '2 onions', protein_g: 0.5, calories_g: 10, estimated_grams: 30, aliases: ['scallion', 'green onion'] },
  { name: 'Kale', portion: '1 serving', protein_g: 3, calories_g: 35, estimated_grams: 70 },
  { name: 'Spring greens', portion: '1 serving', protein_g: 2, calories_g: 25, estimated_grams: 80 },
  { name: 'Ginger', portion: '1 tbsp grated', protein_g: 0.2, calories_g: 5, estimated_grams: 10 },
  { name: 'Chilli', portion: '1 chilli', protein_g: 0.2, calories_g: 4, estimated_grams: 10, aliases: ['chili', 'green chilli', 'red chilli'] },
  { name: 'Jalapeno', portion: '1 pepper', protein_g: 0.2, calories_g: 4, estimated_grams: 14 },
  { name: 'Coriander', portion: '1 handful', protein_g: 0.3, calories_g: 2, estimated_grams: 10, aliases: ['cilantro', 'fresh coriander'] },
  { name: 'Parsley', portion: '1 handful', protein_g: 0.3, calories_g: 4, estimated_grams: 10 },
  { name: 'Basil', portion: '1 handful', protein_g: 0.3, calories_g: 3, estimated_grams: 10 },
  { name: 'Mint', portion: '1 handful', protein_g: 0.3, calories_g: 4, estimated_grams: 10 },
  { name: 'Cumin', portion: '1 tsp', protein_g: 0.5, calories_g: 8, estimated_grams: 2, aliases: ['jeera'] },
  { name: 'Turmeric', portion: '1 tsp', protein_g: 0.3, calories_g: 8, estimated_grams: 2, aliases: ['haldi'] },
  { name: 'Paprika', portion: '1 tsp', protein_g: 0.3, calories_g: 6, estimated_grams: 2 },
  { name: 'Cinnamon', portion: '1 tsp', protein_g: 0.1, calories_g: 6, estimated_grams: 2 },
  { name: 'Cardamom', portion: '1 tsp', protein_g: 0.3, calories_g: 6, estimated_grams: 2, aliases: ['elaichi'] },
  { name: 'Black pepper', portion: '1 tsp', protein_g: 0.2, calories_g: 6, estimated_grams: 2 },
  { name: 'Salt', portion: '1 tsp', protein_g: 0, calories_g: 0, estimated_grams: 6 },
  { name: 'Sugar', portion: '1 tsp', protein_g: 0, calories_g: 16, estimated_grams: 4 },
  { name: 'Brown sugar', portion: '1 tsp', protein_g: 0, calories_g: 15, estimated_grams: 4 },
  { name: 'Flour', portion: '0.25 cup', protein_g: 3, calories_g: 110, estimated_grams: 30, aliases: ['plain flour', 'all purpose flour'] },
  { name: 'Self-raising flour', portion: '0.25 cup', protein_g: 3, calories_g: 110, estimated_grams: 30, aliases: ['self raising flour'] },
  { name: 'Cornflour', portion: '1 tbsp', protein_g: 0, calories_g: 30, estimated_grams: 8, aliases: ['cornstarch'] },
  { name: 'Breadcrumbs', portion: '2 tbsp', protein_g: 2, calories_g: 50, estimated_grams: 15 },
  { name: 'Yeast', portion: '1 tsp', protein_g: 1, calories_g: 10, estimated_grams: 4 },
  { name: 'Baking powder', portion: '1 tsp', protein_g: 0, calories_g: 2, estimated_grams: 4 },
  { name: 'Baking soda', portion: '1 tsp', protein_g: 0, calories_g: 0, estimated_grams: 5, aliases: ['bicarbonate of soda'] },
  { name: 'Vanilla extract', portion: '1 tsp', protein_g: 0, calories_g: 12, estimated_grams: 4 },
  { name: 'Olive oil', portion: '1 tbsp', protein_g: 0, calories_g: 120, estimated_grams: 14 },
  { name: 'Coconut oil', portion: '1 tbsp', protein_g: 0, calories_g: 120, estimated_grams: 14 },
  { name: 'Sunflower oil', portion: '1 tbsp', protein_g: 0, calories_g: 120, estimated_grams: 14 },
  { name: 'Sesame oil', portion: '1 tsp', protein_g: 0, calories_g: 40, estimated_grams: 5 },
  { name: 'Ghee', portion: '1 tbsp', protein_g: 0, calories_g: 120, estimated_grams: 13 },
  { name: 'Butter', portion: '1 tbsp', protein_g: 0.1, calories_g: 100, estimated_grams: 14 },
  { name: 'Rice cake', portion: '1 cake', protein_g: 0.7, calories_g: 35, estimated_grams: 9 },
  { name: 'Cracker', portion: '4 crackers', protein_g: 1.5, calories_g: 70, estimated_grams: 20, aliases: ['cream cracker', 'crackers'] },
  { name: 'Granola', portion: '0.5 cup', protein_g: 5, calories_g: 240, estimated_grams: 55 },
  { name: 'Muesli', portion: '0.5 cup', protein_g: 5, calories_g: 180, estimated_grams: 50 },
  { name: 'Protein bar', portion: '1 bar', protein_g: 20, calories_g: 200, estimated_grams: 60 },
  { name: 'Energy bar', portion: '1 bar', protein_g: 5, calories_g: 220, estimated_grams: 50 },
];
