import type { CatalogFood } from './food-catalog';

/**
 * Second large add-on catalog for Add Ingredient search.
 * Highly specific everyday variants with casual aliases.
 */
export const MORE_FOODS: CatalogFood[] = [
  // —— Dairy / milk variants ——
  {
    name: 'Whole milk (glass)',
    portion: '1 glass',
    protein_g: 8,
    calories_g: 149,
    estimated_grams: 244,
    aliases: ['full cream milk', 'full cream', 'blue top milk', 'whole dairy milk'],
  },
  {
    name: 'Semi-skimmed milk (glass)',
    portion: '1 glass',
    protein_g: 8.4,
    calories_g: 120,
    estimated_grams: 244,
    aliases: ['semi skim', 'semi-skim', 'green top milk', 'semi skimmed'],
  },
  {
    name: 'Skimmed milk (glass)',
    portion: '1 glass',
    protein_g: 8.3,
    calories_g: 83,
    estimated_grams: 245,
    aliases: ['red top milk', 'skinny milk', 'fat-free milk'],
  },
  { name: 'Channel Island milk', portion: '1 cup', protein_g: 8, calories_g: 170, estimated_grams: 244, aliases: ['gold top milk', 'jersey milk'] },
  { name: 'UHT milk', portion: '1 cup', protein_g: 8, calories_g: 120, estimated_grams: 244, aliases: ['long life milk', 'shelf stable milk'] },
  { name: 'Filtered milk', portion: '1 cup', protein_g: 8, calories_g: 120, estimated_grams: 244 },
  { name: 'Chocolate milk (whole)', portion: '1 cup', protein_g: 8, calories_g: 230, estimated_grams: 250, aliases: ['whole chocolate milk', 'full fat choc milk'] },
  { name: 'Chocolate milk (semi-skimmed)', portion: '1 cup', protein_g: 8, calories_g: 190, estimated_grams: 250, aliases: ['semi skimmed chocolate milk', 'light choc milk'] },
  { name: 'Chocolate milk (skimmed)', portion: '1 cup', protein_g: 8, calories_g: 150, estimated_grams: 250, aliases: ['skim chocolate milk', 'diet choc milk'] },
  { name: 'Banana milk', portion: '1 cup', protein_g: 8, calories_g: 180, estimated_grams: 250 },
  { name: 'Vanilla milk', portion: '1 cup', protein_g: 8, calories_g: 170, estimated_grams: 250 },
  { name: 'Malted milk drink', portion: '1 cup', protein_g: 8, calories_g: 200, estimated_grams: 250, aliases: ['horlicks', 'ovaltine', 'malted milk'] },
  { name: 'Oat milk barista', portion: '1 cup', protein_g: 2, calories_g: 140, estimated_grams: 240, aliases: ['barista oat milk', 'oat barista', 'oatly barista'] },
  { name: 'Oat milk unsweetened', portion: '1 cup', protein_g: 2, calories_g: 90, estimated_grams: 240, aliases: ['unsweetened oat milk'] },
  { name: 'Soy milk barista', portion: '1 cup', protein_g: 7, calories_g: 110, estimated_grams: 240, aliases: ['barista soy milk', 'soya barista'] },
  { name: 'Soy milk unsweetened', portion: '1 cup', protein_g: 7, calories_g: 80, estimated_grams: 240, aliases: ['unsweetened soya milk', 'unsweetened soy milk'] },
  { name: 'Almond milk barista', portion: '1 cup', protein_g: 1, calories_g: 50, estimated_grams: 240 },
  { name: 'Coconut cream', portion: '2 tbsp', protein_g: 1, calories_g: 100, estimated_grams: 30 },
  { name: 'Thickened cream', portion: '2 tbsp', protein_g: 0.5, calories_g: 100, estimated_grams: 30 },
  { name: 'Pouring cream', portion: '2 tbsp', protein_g: 0.5, calories_g: 70, estimated_grams: 30 },
  { name: 'Squirty cream', portion: '2 tbsp', protein_g: 0.3, calories_g: 40, estimated_grams: 15, aliases: ['aerosol cream', 'spray cream'] },
  { name: 'Cottage cheese (low fat)', portion: '0.5 cup', protein_g: 14, calories_g: 80, estimated_grams: 110, aliases: ['low fat cottage cheese'] },
  { name: 'Cottage cheese (full fat)', portion: '0.5 cup', protein_g: 12, calories_g: 110, estimated_grams: 110 },
  { name: 'Paneer cubes', portion: '1 serving', protein_g: 18, calories_g: 265, estimated_grams: 100, aliases: ['paneer pieces', 'indian cottage cheese cubes'] },
  { name: 'Homemade paneer', portion: '1 serving', protein_g: 18, calories_g: 270, estimated_grams: 100 },
  { name: 'Low-fat paneer', portion: '1 serving', protein_g: 20, calories_g: 180, estimated_grams: 100, aliases: ['light paneer'] },
  { name: 'Mozzarella (fresh)', portion: '1 ball', protein_g: 14, calories_g: 170, estimated_grams: 100, aliases: ['buffalo mozzarella', 'fresh mozzarella'] },
  { name: 'Mozzarella (grated)', portion: '0.5 cup', protein_g: 12, calories_g: 160, estimated_grams: 56, aliases: ['shredded mozzarella'] },
  { name: 'Cheddar (mild)', portion: '1 slice', protein_g: 7, calories_g: 110, estimated_grams: 28 },
  { name: 'Cheddar (mature)', portion: '1 slice', protein_g: 7, calories_g: 115, estimated_grams: 28, aliases: ['mature cheddar', 'sharp cheddar'] },
  { name: 'Cheddar (extra mature)', portion: '1 slice', protein_g: 7, calories_g: 120, estimated_grams: 28, aliases: ['extra mature cheddar'] },
  { name: 'Red Leicester', portion: '1 slice', protein_g: 7, calories_g: 110, estimated_grams: 28 },
  { name: 'Wensleydale', portion: '1 slice', protein_g: 6, calories_g: 100, estimated_grams: 28 },
  { name: 'Stilton', portion: '1 serving', protein_g: 7, calories_g: 120, estimated_grams: 30, aliases: ['blue stilton'] },
  { name: 'Double Gloucester', portion: '1 slice', protein_g: 7, calories_g: 110, estimated_grams: 28 },
  { name: 'Cornish Yarg', portion: '1 serving', protein_g: 6, calories_g: 100, estimated_grams: 28 },
  { name: 'Emmental', portion: '1 slice', protein_g: 8, calories_g: 110, estimated_grams: 28, aliases: ['emmentaler'] },
  { name: 'Gruyere', portion: '1 slice', protein_g: 8, calories_g: 120, estimated_grams: 28 },
  { name: 'Manchego', portion: '1 serving', protein_g: 7, calories_g: 120, estimated_grams: 28 },
  { name: 'Pecorino', portion: '1 tbsp', protein_g: 3, calories_g: 20, estimated_grams: 5 },
  { name: 'Cottage cheese with pineapple', portion: '1 pot', protein_g: 12, calories_g: 140, estimated_grams: 150 },
  { name: 'Yogurt drink', portion: '1 bottle', protein_g: 5, calories_g: 120, estimated_grams: 200, aliases: ['yakult style', 'probiotic yogurt drink'] },
  { name: 'Activia yogurt', portion: '1 pot', protein_g: 5, calories_g: 100, estimated_grams: 115, aliases: ['activia'] },
  { name: 'Skyr vanilla', portion: '1 pot', protein_g: 15, calories_g: 110, estimated_grams: 150 },
  { name: 'Skyr strawberry', portion: '1 pot', protein_g: 14, calories_g: 120, estimated_grams: 150 },
  { name: 'Protein yogurt strawberry', portion: '1 pot', protein_g: 15, calories_g: 120, estimated_grams: 150 },
  { name: 'Protein yogurt vanilla', portion: '1 pot', protein_g: 15, calories_g: 110, estimated_grams: 150 },
  { name: 'Greek yogurt honey', portion: '1 pot', protein_g: 10, calories_g: 160, estimated_grams: 150 },
  { name: 'Natural yogurt', portion: '1 pot', protein_g: 6, calories_g: 90, estimated_grams: 150, aliases: ['plain yogurt', 'natural yoghurt'] },
  { name: 'Coconut yogurt', portion: '1 pot', protein_g: 1, calories_g: 140, estimated_grams: 125 },
  { name: 'Soy yogurt', portion: '1 pot', protein_g: 5, calories_g: 80, estimated_grams: 125, aliases: ['soya yogurt'] },
  { name: 'Butter (salted)', portion: '1 tbsp', protein_g: 0.1, calories_g: 102, estimated_grams: 14, aliases: ['salted butter'] },
  { name: 'Butter (unsalted)', portion: '1 tbsp', protein_g: 0.1, calories_g: 102, estimated_grams: 14, aliases: ['unsalted butter'] },
  { name: 'Spreadable butter', portion: '1 tbsp', protein_g: 0.1, calories_g: 90, estimated_grams: 14 },
  { name: 'Lurpak', portion: '1 tbsp', protein_g: 0.1, calories_g: 100, estimated_grams: 14 },

  // —— Chocolate specifics ——
  { name: 'Milk chocolate buttons', portion: '1 handful', protein_g: 2, calories_g: 140, estimated_grams: 25, aliases: ['choc buttons', 'chocolate buttons', 'buttons chocolate'] },
  { name: 'Dark chocolate buttons', portion: '1 handful', protein_g: 2, calories_g: 130, estimated_grams: 25 },
  { name: 'White chocolate buttons', portion: '1 handful', protein_g: 1.5, calories_g: 150, estimated_grams: 25 },
  { name: 'Milk chocolate chips', portion: '1 tbsp', protein_g: 0.5, calories_g: 70, estimated_grams: 15, aliases: ['milk choc chips'] },
  { name: 'Dark chocolate chips', portion: '1 tbsp', protein_g: 0.6, calories_g: 65, estimated_grams: 15, aliases: ['dark choc chips'] },
  { name: 'White chocolate chips', portion: '1 tbsp', protein_g: 0.4, calories_g: 75, estimated_grams: 15 },
  { name: 'Chocolate ganache', portion: '2 tbsp', protein_g: 1.5, calories_g: 160, estimated_grams: 40, aliases: ['ganache'] },
  { name: 'Chocolate frosting', portion: '2 tbsp', protein_g: 0.5, calories_g: 140, estimated_grams: 35, aliases: ['choc frosting', 'chocolate icing'] },
  { name: 'Chocolate icing', portion: '2 tbsp', protein_g: 0.5, calories_g: 130, estimated_grams: 35 },
  { name: 'Cocoa nibs', portion: '1 tbsp', protein_g: 1.5, calories_g: 60, estimated_grams: 10, aliases: ['cacao nibs'] },
  { name: '70% dark chocolate', portion: '2 squares', protein_g: 1.8, calories_g: 110, estimated_grams: 20, aliases: ['70 percent chocolate', 'seventy percent chocolate'] },
  { name: '85% dark chocolate', portion: '2 squares', protein_g: 2.2, calories_g: 105, estimated_grams: 20, aliases: ['85 percent chocolate'] },
  { name: '90% dark chocolate', portion: '2 squares', protein_g: 2.5, calories_g: 100, estimated_grams: 20 },
  { name: 'Ruby chocolate', portion: '2 squares', protein_g: 1.2, calories_g: 120, estimated_grams: 20 },
  { name: 'Chocolate truffle', portion: '1 piece', protein_g: 1, calories_g: 70, estimated_grams: 15, aliases: ['truffle chocolate'] },
  { name: 'Chocolate brownie bite', portion: '1 bite', protein_g: 1.5, calories_g: 90, estimated_grams: 25 },
  { name: 'Hot chocolate with marshmallows', portion: '1 cup', protein_g: 8, calories_g: 240, estimated_grams: 260 },
  { name: 'Chocolate protein bar', portion: '1 bar', protein_g: 20, calories_g: 200, estimated_grams: 60, aliases: ['choc protein bar'] },
  { name: 'Chocolate protein shake', portion: '1 shake', protein_g: 25, calories_g: 180, estimated_grams: 330, aliases: ['choc protein shake', 'chocolate whey shake'] },
  { name: 'Chocolate granola', portion: '0.5 cup', protein_g: 5, calories_g: 230, estimated_grams: 50 },
  { name: 'Chocolate cereal', portion: '1 bowl', protein_g: 3, calories_g: 150, estimated_grams: 35, aliases: ['choc cereal'] },
  { name: 'Chocolate covered raisins', portion: '1 handful', protein_g: 1, calories_g: 120, estimated_grams: 30 },
  { name: 'Chocolate covered almonds', portion: '1 handful', protein_g: 4, calories_g: 160, estimated_grams: 30 },
  { name: 'Chocolate digestive', portion: '1 biscuit', protein_g: 1.2, calories_g: 85, estimated_grams: 17, aliases: ['choc digestive', 'chocolate digestives'] },
  { name: 'Chocolate hobnob', portion: '1 biscuit', protein_g: 1.5, calories_g: 90, estimated_grams: 18, aliases: ['choc hobnob'] },
  { name: 'Aero bar', portion: '1 bar', protein_g: 2, calories_g: 200, estimated_grams: 36, aliases: ['aero chocolate'] },
  { name: 'Crunchie', portion: '1 bar', protein_g: 1.5, calories_g: 190, estimated_grams: 40 },
  { name: 'Flake bar', portion: '1 bar', protein_g: 2, calories_g: 180, estimated_grams: 32, aliases: ['cadbury flake'] },
  { name: 'Wispa', portion: '1 bar', protein_g: 2, calories_g: 200, estimated_grams: 36 },
  { name: 'Yorkie', portion: '1 bar', protein_g: 3, calories_g: 240, estimated_grams: 46 },
  { name: 'Picnic bar', portion: '1 bar', protein_g: 3, calories_g: 230, estimated_grams: 48 },
  { name: 'Topic bar', portion: '1 bar', protein_g: 3, calories_g: 220, estimated_grams: 46 },
  { name: 'Double Decker', portion: '1 bar', protein_g: 2.5, calories_g: 250, estimated_grams: 55 },
  { name: 'Boost bar', portion: '1 bar', protein_g: 2.5, calories_g: 240, estimated_grams: 48 },
  { name: 'Milky Way', portion: '1 bar', protein_g: 1.5, calories_g: 180, estimated_grams: 35 },
  { name: 'Lion bar', portion: '1 bar', protein_g: 3, calories_g: 240, estimated_grams: 50 },
  { name: 'Rolo', portion: '1 tube', protein_g: 2, calories_g: 220, estimated_grams: 42, aliases: ['rolos'] },
  { name: 'Quality Street', portion: '2 sweets', protein_g: 1, calories_g: 90, estimated_grams: 18 },
  { name: 'Celebrations', portion: '2 sweets', protein_g: 1.5, calories_g: 100, estimated_grams: 20 },
  { name: 'After Eight', portion: '2 mints', protein_g: 0.5, calories_g: 70, estimated_grams: 16 },
  { name: 'Chocolate fudge', portion: '1 piece', protein_g: 1, calories_g: 110, estimated_grams: 25 },
  { name: 'Chocolate sauce (dessert)', portion: '2 tbsp', protein_g: 0.5, calories_g: 90, estimated_grams: 35 },

  // —— Chicken / meats by cut & prep ——
  {
    name: 'Chicken breast (raw)',
    portion: '1 serving',
    protein_g: 23,
    calories_g: 120,
    estimated_grams: 100,
    aliases: ['chick breast raw', 'raw chicken breast', 'uncooked chicken breast'],
  },
  {
    name: 'Chicken breast (skinless)',
    portion: '1 serving',
    protein_g: 31,
    calories_g: 165,
    estimated_grams: 100,
    aliases: ['chick breast', 'chicken breast skinless', 'skinless chicken breast', 'breast of chicken'],
  },
  { name: 'Chicken breast (with skin)', portion: '1 serving', protein_g: 27, calories_g: 200, estimated_grams: 100 },
  { name: 'Chicken breast (baked)', portion: '1 serving', protein_g: 31, calories_g: 165, estimated_grams: 100, aliases: ['baked chicken breast'] },
  { name: 'Chicken breast (boiled)', portion: '1 serving', protein_g: 30, calories_g: 150, estimated_grams: 100 },
  { name: 'Chicken breast (air fried)', portion: '1 serving', protein_g: 30, calories_g: 170, estimated_grams: 100, aliases: ['air fryer chicken breast'] },
  { name: 'Chicken thigh (skinless)', portion: '1 thigh', protein_g: 22, calories_g: 170, estimated_grams: 100, aliases: ['skinless chicken thigh'] },
  { name: 'Chicken thigh (with skin)', portion: '1 thigh', protein_g: 20, calories_g: 220, estimated_grams: 100 },
  { name: 'Chicken thigh (grilled)', portion: '1 thigh', protein_g: 22, calories_g: 180, estimated_grams: 100 },
  { name: 'Chicken thigh (fried)', portion: '1 thigh', protein_g: 20, calories_g: 250, estimated_grams: 100 },
  { name: 'Chicken thigh (boneless)', portion: '1 thigh', protein_g: 22, calories_g: 180, estimated_grams: 100, aliases: ['boneless chicken thigh'] },
  { name: 'Chicken mince', portion: '1 serving', protein_g: 23, calories_g: 140, estimated_grams: 100, aliases: ['minced chicken', 'ground chicken mince'] },
  { name: 'Chicken mince (cooked)', portion: '1 serving', protein_g: 25, calories_g: 160, estimated_grams: 100 },
  { name: 'Chicken wings (grilled)', portion: '2 wings', protein_g: 14, calories_g: 160, estimated_grams: 60 },
  { name: 'Chicken wings (fried)', portion: '2 wings', protein_g: 12, calories_g: 220, estimated_grams: 60, aliases: ['fried chicken wings', 'buffalo wings'] },
  { name: 'Chicken wings (BBQ)', portion: '2 wings', protein_g: 13, calories_g: 200, estimated_grams: 70 },
  { name: 'Chicken drumstick (grilled)', portion: '1 drumstick', protein_g: 12, calories_g: 110, estimated_grams: 50 },
  { name: 'Chicken drumstick (fried)', portion: '1 drumstick', protein_g: 11, calories_g: 160, estimated_grams: 55 },
  { name: 'Chicken fillet', portion: '1 fillet', protein_g: 30, calories_g: 165, estimated_grams: 100, aliases: ['chicken filet'] },
  { name: 'Chicken goujons', portion: '3 pieces', protein_g: 15, calories_g: 220, estimated_grams: 90, aliases: ['chicken goujon'] },
  { name: 'Chicken popcorn', portion: '1 serving', protein_g: 18, calories_g: 280, estimated_grams: 100 },
  { name: 'Chicken 65', portion: '1 serving', protein_g: 22, calories_g: 280, estimated_grams: 150 },
  { name: 'Chicken lollipop', portion: '2 pieces', protein_g: 14, calories_g: 220, estimated_grams: 80 },
  { name: 'Tandoori chicken', portion: '1 piece', protein_g: 25, calories_g: 220, estimated_grams: 120 },
  { name: 'Chicken seekh kebab', portion: '1 skewer', protein_g: 18, calories_g: 180, estimated_grams: 80 },
  { name: 'Chicken malai tikka', portion: '1 serving', protein_g: 24, calories_g: 260, estimated_grams: 130 },
  { name: 'Chicken curry (boneless)', portion: '1 bowl', protein_g: 24, calories_g: 300, estimated_grams: 220 },
  { name: 'Chicken curry (with bone)', portion: '1 bowl', protein_g: 20, calories_g: 280, estimated_grams: 240 },
  { name: 'Chicken korma', portion: '1 bowl', protein_g: 22, calories_g: 400, estimated_grams: 250 },
  { name: 'Chicken jalfrezi', portion: '1 bowl', protein_g: 24, calories_g: 320, estimated_grams: 240 },
  { name: 'Chicken madras', portion: '1 bowl', protein_g: 24, calories_g: 340, estimated_grams: 240 },
  { name: 'Chicken rogan josh', portion: '1 bowl', protein_g: 24, calories_g: 350, estimated_grams: 240 },
  { name: 'Chicken bhuna', portion: '1 bowl', protein_g: 24, calories_g: 330, estimated_grams: 240 },
  { name: 'Chicken vindaloo', portion: '1 bowl', protein_g: 24, calories_g: 340, estimated_grams: 240 },
  { name: 'Chicken saag', portion: '1 bowl', protein_g: 24, calories_g: 300, estimated_grams: 240, aliases: ['saag chicken', 'palak chicken'] },
  { name: 'Chicken chettinad', portion: '1 bowl', protein_g: 24, calories_g: 320, estimated_grams: 240 },
  { name: 'Chicken 65 rice bowl', portion: '1 bowl', protein_g: 28, calories_g: 520, estimated_grams: 400 },
  { name: 'Turkey mince', portion: '1 serving', protein_g: 27, calories_g: 150, estimated_grams: 100, aliases: ['minced turkey', 'ground turkey mince'] },
  { name: 'Turkey thigh', portion: '1 serving', protein_g: 24, calories_g: 180, estimated_grams: 100 },
  { name: 'Duck breast', portion: '1 serving', protein_g: 19, calories_g: 280, estimated_grams: 100 },
  { name: 'Duck confit', portion: '1 serving', protein_g: 18, calories_g: 400, estimated_grams: 100 },
  {
    name: 'Streaky bacon',
    portion: '2 rashers',
    protein_g: 8,
    calories_g: 140,
    estimated_grams: 30,
    aliases: ['bacon streaky', 'streaky bacon rasher', 'american bacon'],
  },
  {
    name: 'Back bacon',
    portion: '2 rashers',
    protein_g: 12,
    calories_g: 100,
    estimated_grams: 40,
    aliases: ['bacon back', 'british bacon', 'back bacon rasher'],
  },
  { name: 'Bacon (grilled)', portion: '2 rashers', protein_g: 10, calories_g: 90, estimated_grams: 30, aliases: ['grilled bacon'] },
  { name: 'Bacon (fried)', portion: '2 rashers', protein_g: 9, calories_g: 130, estimated_grams: 30, aliases: ['fried bacon'] },
  { name: 'Turkey bacon', portion: '2 rashers', protein_g: 8, calories_g: 70, estimated_grams: 30 },
  { name: 'Bacon bits', portion: '1 tbsp', protein_g: 3, calories_g: 30, estimated_grams: 7 },
  { name: 'Gammon steak', portion: '1 steak', protein_g: 30, calories_g: 250, estimated_grams: 150, aliases: ['gammon'] },
  { name: 'Gammon joint', portion: '1 serving', protein_g: 25, calories_g: 220, estimated_grams: 100 },
  { name: 'Pork loin', portion: '1 serving', protein_g: 27, calories_g: 180, estimated_grams: 100 },
  { name: 'Pork mince', portion: '1 serving', protein_g: 25, calories_g: 260, estimated_grams: 100, aliases: ['minced pork', 'ground pork'] },
  { name: 'Pork sausage', portion: '1 sausage', protein_g: 8, calories_g: 160, estimated_grams: 55, aliases: ['banger', 'british sausage'] },
  { name: 'Cumberland sausage', portion: '1 sausage', protein_g: 10, calories_g: 200, estimated_grams: 70 },
  { name: 'Lincolnshire sausage', portion: '1 sausage', protein_g: 9, calories_g: 180, estimated_grams: 60 },
  { name: 'Chicken sausage', portion: '1 sausage', protein_g: 12, calories_g: 120, estimated_grams: 55 },
  { name: 'Vegetarian sausage', portion: '1 sausage', protein_g: 8, calories_g: 110, estimated_grams: 50, aliases: ['veggie sausage', 'meat free sausage'] },
  { name: 'Black pudding', portion: '1 slice', protein_g: 5, calories_g: 100, estimated_grams: 35 },
  { name: 'White pudding', portion: '1 slice', protein_g: 4, calories_g: 110, estimated_grams: 35 },
  { name: 'Haggis', portion: '1 serving', protein_g: 12, calories_g: 250, estimated_grams: 100 },
  { name: 'Steak (rump)', portion: '1 steak', protein_g: 38, calories_g: 300, estimated_grams: 150, aliases: ['rump steak'] },
  { name: 'Steak (fillet)', portion: '1 steak', protein_g: 36, calories_g: 280, estimated_grams: 150, aliases: ['fillet steak', 'filet mignon'] },
  { name: 'Steak (T-bone)', portion: '1 steak', protein_g: 45, calories_g: 450, estimated_grams: 200, aliases: ['t bone steak', 'tbone'] },
  { name: 'Steak (flank)', portion: '1 serving', protein_g: 28, calories_g: 200, estimated_grams: 100, aliases: ['flank steak'] },
  { name: 'Steak (skirt)', portion: '1 serving', protein_g: 26, calories_g: 220, estimated_grams: 100 },
  { name: 'Minced beef (5% fat)', portion: '1 serving', protein_g: 28, calories_g: 140, estimated_grams: 100, aliases: ['extra lean mince', '5% mince'] },
  { name: 'Minced beef (10% fat)', portion: '1 serving', protein_g: 26, calories_g: 180, estimated_grams: 100, aliases: ['10% mince', 'lean mince'] },
  { name: 'Minced beef (20% fat)', portion: '1 serving', protein_g: 24, calories_g: 250, estimated_grams: 100, aliases: ['20% mince'] },
  { name: 'Beef brisket', portion: '1 serving', protein_g: 24, calories_g: 280, estimated_grams: 100 },
  { name: 'Beef short ribs', portion: '1 serving', protein_g: 22, calories_g: 350, estimated_grams: 120 },
  { name: 'Beef mince curry', portion: '1 bowl', protein_g: 22, calories_g: 320, estimated_grams: 220, aliases: ['keema', 'keema curry'] },
  { name: 'Lamb mince', portion: '1 serving', protein_g: 25, calories_g: 280, estimated_grams: 100, aliases: ['minced lamb', 'ground lamb'] },
  { name: 'Lamb shoulder', portion: '1 serving', protein_g: 24, calories_g: 280, estimated_grams: 100 },
  { name: 'Lamb leg', portion: '1 serving', protein_g: 26, calories_g: 240, estimated_grams: 100 },
  { name: 'Lamb rogan josh', portion: '1 bowl', protein_g: 26, calories_g: 380, estimated_grams: 250 },
  { name: 'Mutton curry', portion: '1 bowl', protein_g: 26, calories_g: 400, estimated_grams: 250 },
  { name: 'Goat curry', portion: '1 bowl', protein_g: 25, calories_g: 350, estimated_grams: 240, aliases: ['mutton goat curry'] },

  // —— Fish / seafood specifics ——
  { name: 'Salmon fillet (raw)', portion: '1 fillet', protein_g: 20, calories_g: 180, estimated_grams: 100 },
  { name: 'Salmon fillet (grilled)', portion: '1 fillet', protein_g: 22, calories_g: 200, estimated_grams: 100, aliases: ['grilled salmon'] },
  { name: 'Salmon fillet (baked)', portion: '1 fillet', protein_g: 22, calories_g: 200, estimated_grams: 100, aliases: ['baked salmon'] },
  { name: 'Salmon fillet (fried)', portion: '1 fillet', protein_g: 21, calories_g: 250, estimated_grams: 100 },
  { name: 'Salmon skin', portion: '1 serving', protein_g: 8, calories_g: 150, estimated_grams: 30 },
  { name: 'Smoked mackerel', portion: '1 fillet', protein_g: 18, calories_g: 220, estimated_grams: 90 },
  { name: 'Kippers', portion: '1 fillet', protein_g: 18, calories_g: 180, estimated_grams: 85 },
  { name: 'Cod fillet (baked)', portion: '1 fillet', protein_g: 20, calories_g: 90, estimated_grams: 100 },
  { name: 'Cod fillet (battered)', portion: '1 fillet', protein_g: 18, calories_g: 250, estimated_grams: 150, aliases: ['battered cod', 'fish shop cod'] },
  { name: 'Haddock (smoked)', portion: '1 fillet', protein_g: 20, calories_g: 100, estimated_grams: 100, aliases: ['smoked haddock'] },
  { name: 'Haddock (battered)', portion: '1 fillet', protein_g: 18, calories_g: 260, estimated_grams: 150 },
  { name: 'Plaice', portion: '1 fillet', protein_g: 18, calories_g: 90, estimated_grams: 100 },
  { name: 'Sole', portion: '1 fillet', protein_g: 18, calories_g: 85, estimated_grams: 100, aliases: ['dover sole', 'lemon sole'] },
  { name: 'Halibut', portion: '1 fillet', protein_g: 21, calories_g: 110, estimated_grams: 100 },
  { name: 'Swordfish', portion: '1 steak', protein_g: 23, calories_g: 140, estimated_grams: 100 },
  { name: 'Prawns (cooked)', portion: '1 serving', protein_g: 20, calories_g: 100, estimated_grams: 100, aliases: ['cooked prawns', 'shrimp cooked'] },
  { name: 'Prawns (fried)', portion: '1 serving', protein_g: 18, calories_g: 200, estimated_grams: 100, aliases: ['fried prawns', 'fried shrimp'] },
  { name: 'King prawns', portion: '1 serving', protein_g: 22, calories_g: 110, estimated_grams: 100, aliases: ['tiger prawns'] },
  { name: 'Prawn curry', portion: '1 bowl', protein_g: 20, calories_g: 280, estimated_grams: 220, aliases: ['shrimp curry'] },
  { name: 'Garlic prawns', portion: '1 serving', protein_g: 20, calories_g: 220, estimated_grams: 120 },
  { name: 'Scampi', portion: '1 serving', protein_g: 12, calories_g: 280, estimated_grams: 100 },
  { name: 'Crab sticks', portion: '3 sticks', protein_g: 4, calories_g: 60, estimated_grams: 45, aliases: ['surimi'] },
  { name: 'Imitation crab', portion: '1 serving', protein_g: 7, calories_g: 90, estimated_grams: 85 },
  { name: 'Tuna mayo', portion: '1 serving', protein_g: 18, calories_g: 220, estimated_grams: 100, aliases: ['tuna mayonnaise', 'tuna salad mix'] },
  { name: 'Tuna melt', portion: '1 sandwich', protein_g: 22, calories_g: 400, estimated_grams: 180 },
  { name: 'Fish cake', portion: '1 cake', protein_g: 8, calories_g: 150, estimated_grams: 70 },
  { name: 'Fish pie', portion: '1 serving', protein_g: 18, calories_g: 350, estimated_grams: 250 },
  { name: 'Seafood paella', portion: '1 plate', protein_g: 22, calories_g: 450, estimated_grams: 350 },
  { name: 'Calamari rings', portion: '1 serving', protein_g: 14, calories_g: 220, estimated_grams: 100 },
  { name: 'Clams', portion: '1 serving', protein_g: 12, calories_g: 80, estimated_grams: 100 },
  { name: 'Cockles', portion: '1 serving', protein_g: 12, calories_g: 80, estimated_grams: 80 },
  { name: 'Whelks', portion: '1 serving', protein_g: 15, calories_g: 90, estimated_grams: 80 },
  { name: 'Eel', portion: '1 serving', protein_g: 18, calories_g: 180, estimated_grams: 100 },
  { name: 'Jellied eels', portion: '1 serving', protein_g: 16, calories_g: 150, estimated_grams: 100 },

  // —— Indian dishes + staples ——
  { name: 'Paneer bhurji', portion: '1 serving', protein_g: 16, calories_g: 280, estimated_grams: 150, aliases: ['bhurji paneer'] },
  { name: 'Paneer curry', portion: '1 bowl', protein_g: 16, calories_g: 320, estimated_grams: 220 },
  { name: 'Kadai paneer', portion: '1 bowl', protein_g: 16, calories_g: 340, estimated_grams: 220, aliases: ['karahi paneer'] },
  { name: 'Shahi paneer', portion: '1 bowl', protein_g: 15, calories_g: 360, estimated_grams: 220 },
  { name: 'Matar paneer', portion: '1 bowl', protein_g: 14, calories_g: 300, estimated_grams: 220, aliases: ['mutter paneer', 'peas paneer'] },
  { name: 'Paneer do pyaza', portion: '1 bowl', protein_g: 15, calories_g: 320, estimated_grams: 220 },
  { name: 'Paneer wrap', portion: '1 wrap', protein_g: 18, calories_g: 380, estimated_grams: 220 },
  { name: 'Paneer sandwich', portion: '1 sandwich', protein_g: 16, calories_g: 350, estimated_grams: 180 },
  { name: 'Malai kofta', portion: '1 bowl', protein_g: 12, calories_g: 380, estimated_grams: 220 },
  { name: 'Dal tadka', portion: '1 bowl', protein_g: 9, calories_g: 180, estimated_grams: 200, aliases: ['tadka dal'] },
  { name: 'Dal fry', portion: '1 bowl', protein_g: 9, calories_g: 190, estimated_grams: 200 },
  { name: 'Yellow dal', portion: '1 bowl', protein_g: 9, calories_g: 160, estimated_grams: 200 },
  { name: 'Sambar rice', portion: '1 plate', protein_g: 8, calories_g: 320, estimated_grams: 300 },
  { name: 'Rasam rice', portion: '1 plate', protein_g: 5, calories_g: 250, estimated_grams: 280 },
  { name: 'Tomato rice', portion: '1 plate', protein_g: 5, calories_g: 280, estimated_grams: 220 },
  { name: 'Coconut rice', portion: '1 plate', protein_g: 5, calories_g: 320, estimated_grams: 220 },
  { name: 'Tamarind rice', portion: '1 plate', protein_g: 4, calories_g: 300, estimated_grams: 220, aliases: ['puliyodarai', 'pulihora'] },
  { name: 'Jeera rice', portion: '1 plate', protein_g: 4, calories_g: 250, estimated_grams: 200, aliases: ['cumin rice'] },
  { name: 'Peas pulao', portion: '1 plate', protein_g: 7, calories_g: 300, estimated_grams: 220 },
  { name: 'Egg biryani', portion: '1 plate', protein_g: 16, calories_g: 420, estimated_grams: 300 },
  { name: 'Prawn biryani', portion: '1 plate', protein_g: 20, calories_g: 450, estimated_grams: 320 },
  { name: 'Hyderabadi biryani', portion: '1 plate', protein_g: 24, calories_g: 520, estimated_grams: 350 },
  { name: 'Dum biryani', portion: '1 plate', protein_g: 22, calories_g: 500, estimated_grams: 340 },
  { name: 'Fish fry (Indian)', portion: '1 piece', protein_g: 20, calories_g: 250, estimated_grams: 120, aliases: ['indian fish fry'] },
  { name: 'Egg bhurji', portion: '1 serving', protein_g: 14, calories_g: 220, estimated_grams: 150, aliases: ['anda bhurji', 'indian scrambled egg'] },
  { name: 'Boiled egg curry', portion: '1 serving', protein_g: 14, calories_g: 240, estimated_grams: 200 },
  { name: 'Aloo sabzi', portion: '1 bowl', protein_g: 3, calories_g: 180, estimated_grams: 180, aliases: ['potato sabzi', 'aloo curry'] },
  { name: 'Bhindi masala', portion: '1 bowl', protein_g: 4, calories_g: 160, estimated_grams: 180, aliases: ['okra masala'] },
  { name: 'Baingan bharta', portion: '1 bowl', protein_g: 3, calories_g: 150, estimated_grams: 180, aliases: ['brinjal bharta'] },
  { name: 'Gobi manchurian', portion: '1 serving', protein_g: 5, calories_g: 280, estimated_grams: 150 },
  { name: 'Chilli paneer', portion: '1 serving', protein_g: 16, calories_g: 320, estimated_grams: 180, aliases: ['chili paneer'] },
  { name: 'Chilli chicken', portion: '1 serving', protein_g: 24, calories_g: 350, estimated_grams: 180, aliases: ['chili chicken'] },
  { name: 'Hakka noodles', portion: '1 plate', protein_g: 10, calories_g: 400, estimated_grams: 280 },
  { name: 'Schezwan noodles', portion: '1 plate', protein_g: 10, calories_g: 420, estimated_grams: 280, aliases: ['schezwan fried noodles'] },
  { name: 'Schezwan rice', portion: '1 plate', protein_g: 8, calories_g: 400, estimated_grams: 280 },
  { name: 'Manchurian gravy', portion: '1 serving', protein_g: 6, calories_g: 220, estimated_grams: 180 },
  { name: 'Idli sambar', portion: '2 idli with sambar', protein_g: 8, calories_g: 180, estimated_grams: 200 },
  { name: 'Rava idli', portion: '1 idli', protein_g: 2.5, calories_g: 60, estimated_grams: 40 },
  { name: 'Set dosa', portion: '1 set', protein_g: 6, calories_g: 200, estimated_grams: 120 },
  { name: 'Onion dosa', portion: '1 large', protein_g: 6, calories_g: 220, estimated_grams: 130 },
  { name: 'Cheese dosa', portion: '1 large', protein_g: 12, calories_g: 320, estimated_grams: 150 },
  { name: 'Paper dosa', portion: '1 large', protein_g: 5, calories_g: 180, estimated_grams: 100 },
  { name: 'Ghee roast dosa', portion: '1 large', protein_g: 6, calories_g: 280, estimated_grams: 120 },
  { name: 'Pesarattu', portion: '1 large', protein_g: 8, calories_g: 200, estimated_grams: 110 },
  { name: 'Mysore dosa', portion: '1 large', protein_g: 6, calories_g: 230, estimated_grams: 130 },
  { name: 'Onion uttapam', portion: '1 uttapam', protein_g: 5, calories_g: 200, estimated_grams: 110 },
  { name: 'Tomato uttapam', portion: '1 uttapam', protein_g: 5, calories_g: 190, estimated_grams: 110 },
  { name: 'Methi paratha', portion: '1 paratha', protein_g: 5, calories_g: 200, estimated_grams: 80 },
  { name: 'Paneer paratha', portion: '1 paratha', protein_g: 10, calories_g: 300, estimated_grams: 120 },
  { name: 'Onion paratha', portion: '1 paratha', protein_g: 5, calories_g: 230, estimated_grams: 100 },
  { name: 'Laccha paratha', portion: '1 paratha', protein_g: 5, calories_g: 260, estimated_grams: 90 },
  { name: 'Tandoori roti', portion: '1 roti', protein_g: 3.5, calories_g: 120, estimated_grams: 45 },
  { name: 'Missi roti', portion: '1 roti', protein_g: 5, calories_g: 140, estimated_grams: 50 },
  { name: 'Roomali roti', portion: '1 roti', protein_g: 3, calories_g: 110, estimated_grams: 40 },
  { name: 'Kulcha', portion: '1 kulcha', protein_g: 6, calories_g: 200, estimated_grams: 70 },
  { name: 'Amritsari kulcha', portion: '1 kulcha', protein_g: 7, calories_g: 250, estimated_grams: 90 },
  { name: 'Cheese naan', portion: '1 naan', protein_g: 12, calories_g: 340, estimated_grams: 110 },
  { name: 'Peshwari naan', portion: '1 naan', protein_g: 8, calories_g: 320, estimated_grams: 100 },
  { name: 'Keema naan', portion: '1 naan', protein_g: 14, calories_g: 360, estimated_grams: 120 },
  { name: 'Chole kulche', portion: '1 plate', protein_g: 14, calories_g: 450, estimated_grams: 320 },
  { name: 'Rajma chawal', portion: '1 plate', protein_g: 12, calories_g: 400, estimated_grams: 350, aliases: ['rajma rice'] },
  { name: 'Kadhi chawal', portion: '1 plate', protein_g: 10, calories_g: 380, estimated_grams: 350, aliases: ['kadhi rice'] },
  { name: 'Kadhi', portion: '1 bowl', protein_g: 6, calories_g: 150, estimated_grams: 200, aliases: ['punjabi kadhi'] },
  { name: 'Aloo tikki', portion: '1 tikki', protein_g: 2, calories_g: 120, estimated_grams: 60 },
  { name: 'Dahi puri', portion: '6 pieces', protein_g: 4, calories_g: 220, estimated_grams: 140 },
  { name: 'Sev puri', portion: '6 pieces', protein_g: 3, calories_g: 200, estimated_grams: 130 },
  { name: 'Ragda pattice', portion: '1 serving', protein_g: 8, calories_g: 280, estimated_grams: 200 },
  { name: 'Pav', portion: '1 pav', protein_g: 3, calories_g: 100, estimated_grams: 40, aliases: ['ladi pav', 'burger pav'] },
  { name: 'Bun maska', portion: '1 bun', protein_g: 4, calories_g: 220, estimated_grams: 70 },
  { name: 'Irani chai', portion: '1 cup', protein_g: 3, calories_g: 100, estimated_grams: 180 },
  { name: 'Filter coffee', portion: '1 cup', protein_g: 1, calories_g: 40, estimated_grams: 150, aliases: ['south indian filter coffee', 'kaapi'] },
  { name: 'Buttermilk (chaas)', portion: '1 glass', protein_g: 3, calories_g: 50, estimated_grams: 200, aliases: ['chaas', 'chhas'] },
  { name: 'Sweet lassi', portion: '1 glass', protein_g: 6, calories_g: 200, estimated_grams: 280 },
  { name: 'Salted lassi', portion: '1 glass', protein_g: 6, calories_g: 120, estimated_grams: 250 },
  { name: 'Masala omelette', portion: '1 omelette', protein_g: 14, calories_g: 220, estimated_grams: 120 },
  { name: 'Egg toast (Indian)', portion: '1 serving', protein_g: 12, calories_g: 280, estimated_grams: 150 },
  { name: 'Upma (rava)', portion: '1 serving', protein_g: 4, calories_g: 200, estimated_grams: 150 },
  { name: 'Poha with peanuts', portion: '1 serving', protein_g: 5, calories_g: 220, estimated_grams: 160 },
  { name: 'Sabudana khichdi', portion: '1 serving', protein_g: 3, calories_g: 280, estimated_grams: 180 },
  { name: 'Thali (veg)', portion: '1 thali', protein_g: 20, calories_g: 700, estimated_grams: 600, aliases: ['veg thali', 'indian thali'] },
  { name: 'Thali (non-veg)', portion: '1 thali', protein_g: 35, calories_g: 850, estimated_grams: 650, aliases: ['non veg thali'] },
  { name: 'Roti sabzi', portion: '1 plate', protein_g: 10, calories_g: 350, estimated_grams: 280 },
  { name: 'Dal rice', portion: '1 plate', protein_g: 10, calories_g: 350, estimated_grams: 320, aliases: ['dal chawal'] },
  { name: 'Ghee rice', portion: '1 plate', protein_g: 5, calories_g: 350, estimated_grams: 220 },
  { name: 'Chicken 65 starter', portion: '1 serving', protein_g: 22, calories_g: 300, estimated_grams: 150 },
  { name: 'Fish moilee', portion: '1 bowl', protein_g: 22, calories_g: 320, estimated_grams: 220, aliases: ['fish molee'] },
  { name: 'Kerala fish curry', portion: '1 bowl', protein_g: 22, calories_g: 300, estimated_grams: 220 },
  { name: 'Bengali fish curry', portion: '1 bowl', protein_g: 22, calories_g: 280, estimated_grams: 220, aliases: ['machher jhol'] },
  { name: 'Ilish fry', portion: '1 piece', protein_g: 20, calories_g: 280, estimated_grams: 100, aliases: ['hilsa fry'] },
  { name: 'Rosogolla', portion: '1 piece', protein_g: 1.5, calories_g: 100, estimated_grams: 40 },
  { name: 'Sandesh', portion: '1 piece', protein_g: 3, calories_g: 120, estimated_grams: 30 },
  { name: 'Mysore pak', portion: '1 piece', protein_g: 2, calories_g: 180, estimated_grams: 35 },
  { name: 'Soan papdi', portion: '1 piece', protein_g: 1.5, calories_g: 140, estimated_grams: 30 },
  { name: 'Besan ladoo', portion: '1 ladoo', protein_g: 3, calories_g: 160, estimated_grams: 35 },
  { name: 'Motichoor ladoo', portion: '1 ladoo', protein_g: 2.5, calories_g: 170, estimated_grams: 35 },
  { name: 'Gajar halwa', portion: '1 serving', protein_g: 4, calories_g: 280, estimated_grams: 120, aliases: ['carrot halwa'] },
  { name: 'Sooji halwa', portion: '1 serving', protein_g: 3, calories_g: 250, estimated_grams: 100, aliases: ['rava halwa', 'semolina halwa'] },
  { name: 'Payasam', portion: '1 bowl', protein_g: 5, calories_g: 220, estimated_grams: 180 },
  { name: 'Phirni', portion: '1 bowl', protein_g: 5, calories_g: 200, estimated_grams: 150 },

  // —— UK supermarket / breakfast / bakery ——
  { name: 'Weetabix with milk', portion: '2 biscuits + milk', protein_g: 10, calories_g: 220, estimated_grams: 250 },
  { name: 'Porridge with milk', portion: '1 bowl', protein_g: 9, calories_g: 220, estimated_grams: 250, aliases: ['oat porridge with milk'] },
  { name: 'Porridge with water', portion: '1 bowl', protein_g: 5, calories_g: 150, estimated_grams: 200 },
  { name: 'Porridge with honey', portion: '1 bowl', protein_g: 5, calories_g: 220, estimated_grams: 220 },
  { name: 'Porridge with banana', portion: '1 bowl', protein_g: 6, calories_g: 280, estimated_grams: 280 },
  { name: 'Porridge with peanut butter', portion: '1 bowl', protein_g: 10, calories_g: 320, estimated_grams: 250 },
  { name: 'Protein porridge', portion: '1 bowl', protein_g: 20, calories_g: 280, estimated_grams: 250 },
  {
    name: 'Oats (dry)',
    portion: '40 g',
    protein_g: 5,
    calories_g: 150,
    estimated_grams: 40,
    aliases: ['dry oats', 'raw oats', 'oatmeal dry', 'porridge oats'],
  },
  {
    name: 'Oats (cooked)',
    portion: '1 bowl',
    protein_g: 5,
    calories_g: 150,
    estimated_grams: 200,
    aliases: ['cooked oats', 'oatmeal cooked', 'oats porridge'],
  },
  { name: 'Jumbo oats', portion: '1 serving', protein_g: 5, calories_g: 150, estimated_grams: 40, aliases: ['jumbo rolled oats'] },
  { name: 'Pinhead oats', portion: '1 serving', protein_g: 5, calories_g: 150, estimated_grams: 40, aliases: ['steel cut porridge oats'] },
  { name: 'Oat bran', portion: '2 tbsp', protein_g: 3, calories_g: 50, estimated_grams: 15 },
  { name: 'Ready Brek', portion: '1 bowl', protein_g: 5, calories_g: 160, estimated_grams: 200 },
  { name: 'Alpen muesli', portion: '1 serving', protein_g: 5, calories_g: 180, estimated_grams: 50 },
  { name: 'Special K', portion: '1 bowl', protein_g: 4, calories_g: 120, estimated_grams: 30 },
  { name: 'Frosties', portion: '1 bowl', protein_g: 1.5, calories_g: 140, estimated_grams: 30 },
  { name: 'Crunchy Nut', portion: '1 bowl', protein_g: 2.5, calories_g: 150, estimated_grams: 30 },
  { name: 'Bran Flakes', portion: '1 bowl', protein_g: 4, calories_g: 120, estimated_grams: 30 },
  { name: 'Fruit and Fibre', portion: '1 bowl', protein_g: 3, calories_g: 140, estimated_grams: 35 },
  { name: 'Shreddies', portion: '1 bowl', protein_g: 3.5, calories_g: 140, estimated_grams: 35 },
  { name: 'Honey Loops', portion: '1 bowl', protein_g: 2, calories_g: 140, estimated_grams: 30 },
  { name: 'Granola with yogurt', portion: '1 bowl', protein_g: 10, calories_g: 320, estimated_grams: 220 },
  { name: 'Greek yogurt granola bowl', portion: '1 bowl', protein_g: 18, calories_g: 350, estimated_grams: 250 },
  { name: 'Toast with butter', portion: '1 slice', protein_g: 3, calories_g: 150, estimated_grams: 40 },
  { name: 'Toast with jam', portion: '1 slice', protein_g: 2.5, calories_g: 160, estimated_grams: 45 },
  { name: 'Toast with peanut butter', portion: '1 slice', protein_g: 7, calories_g: 220, estimated_grams: 50 },
  { name: 'Toast with Marmite', portion: '1 slice', protein_g: 4, calories_g: 120, estimated_grams: 40, aliases: ['marmite on toast'] },
  { name: 'Toast with avocado', portion: '1 slice', protein_g: 5, calories_g: 220, estimated_grams: 100 },
  { name: 'Toast with eggs', portion: '1 serving', protein_g: 14, calories_g: 280, estimated_grams: 150, aliases: ['eggs on toast'] },
  { name: 'Crumpet with butter', portion: '1 crumpet', protein_g: 3.5, calories_g: 140, estimated_grams: 50 },
  { name: 'English muffin with egg', portion: '1 muffin', protein_g: 12, calories_g: 250, estimated_grams: 120 },
  { name: 'Bacon sandwich', portion: '1 sandwich', protein_g: 18, calories_g: 400, estimated_grams: 180, aliases: ['bacon butty', 'bacon sarnie'] },
  { name: 'Sausage sandwich', portion: '1 sandwich', protein_g: 16, calories_g: 420, estimated_grams: 200, aliases: ['sausage butty', 'sausage sarnie'] },
  { name: 'Egg sandwich', portion: '1 sandwich', protein_g: 14, calories_g: 350, estimated_grams: 160, aliases: ['egg mayo sandwich', 'egg mayonnaise sandwich'] },
  { name: 'Cheese sandwich', portion: '1 sandwich', protein_g: 14, calories_g: 380, estimated_grams: 160 },
  { name: 'Ham sandwich', portion: '1 sandwich', protein_g: 16, calories_g: 320, estimated_grams: 160 },
  { name: 'Ham and cheese sandwich', portion: '1 sandwich', protein_g: 20, calories_g: 400, estimated_grams: 180 },
  { name: 'Tuna sandwich', portion: '1 sandwich', protein_g: 20, calories_g: 380, estimated_grams: 180 },
  { name: 'Chicken sandwich', portion: '1 sandwich', protein_g: 22, calories_g: 400, estimated_grams: 200 },
  { name: 'Ploughmans sandwich', portion: '1 sandwich', protein_g: 16, calories_g: 420, estimated_grams: 200 },
  { name: 'Meal deal sandwich', portion: '1 sandwich', protein_g: 18, calories_g: 400, estimated_grams: 180 },
  { name: 'Meal deal wrap', portion: '1 wrap', protein_g: 20, calories_g: 420, estimated_grams: 200 },
  { name: 'Meal deal salad', portion: '1 pot', protein_g: 15, calories_g: 300, estimated_grams: 250 },
  { name: 'Pret sandwich', portion: '1 sandwich', protein_g: 20, calories_g: 420, estimated_grams: 200 },
  { name: 'Greggs sausage roll', portion: '1 roll', protein_g: 9, calories_g: 320, estimated_grams: 105 },
  { name: 'Greggs steak bake', portion: '1 bake', protein_g: 14, calories_g: 400, estimated_grams: 140 },
  { name: 'Greggs chicken bake', portion: '1 bake', protein_g: 14, calories_g: 380, estimated_grams: 140 },
  { name: 'Greggs vegan sausage roll', portion: '1 roll', protein_g: 6, calories_g: 300, estimated_grams: 100 },
  { name: 'Pastie', portion: '1 pastie', protein_g: 12, calories_g: 400, estimated_grams: 180 },
  { name: 'Pork pie', portion: '1 pie', protein_g: 12, calories_g: 350, estimated_grams: 140 },
  { name: 'Meat pie', portion: '1 pie', protein_g: 16, calories_g: 450, estimated_grams: 200 },
  { name: 'Chicken pie', portion: '1 pie', protein_g: 18, calories_g: 420, estimated_grams: 200 },
  { name: 'Shepherd\'s pie', portion: '1 serving', protein_g: 18, calories_g: 380, estimated_grams: 280, aliases: ['shepherds pie'] },
  { name: 'Cottage pie', portion: '1 serving', protein_g: 18, calories_g: 370, estimated_grams: 280 },
  { name: 'Toad in the hole', portion: '1 serving', protein_g: 18, calories_g: 450, estimated_grams: 250 },
  { name: 'Yorkshire pudding', portion: '1 pudding', protein_g: 3, calories_g: 100, estimated_grams: 40 },
  { name: 'Sunday roast', portion: '1 plate', protein_g: 35, calories_g: 800, estimated_grams: 500 },
  { name: 'Roast chicken dinner', portion: '1 plate', protein_g: 35, calories_g: 700, estimated_grams: 450 },
  { name: 'Roast beef dinner', portion: '1 plate', protein_g: 38, calories_g: 750, estimated_grams: 450 },
  { name: 'Roast lamb dinner', portion: '1 plate', protein_g: 36, calories_g: 780, estimated_grams: 450 },
  { name: 'Bubble and squeak', portion: '1 serving', protein_g: 5, calories_g: 200, estimated_grams: 150 },
  { name: 'Bangers and mash', portion: '1 plate', protein_g: 20, calories_g: 550, estimated_grams: 400 },
  { name: 'Fish finger sandwich', portion: '1 sandwich', protein_g: 14, calories_g: 380, estimated_grams: 180 },
  { name: 'Chip butty', portion: '1 sandwich', protein_g: 8, calories_g: 500, estimated_grams: 250, aliases: ['chip sandwich'] },
  { name: 'Cheese and onion crisps', portion: '1 bag', protein_g: 2, calories_g: 150, estimated_grams: 30 },
  { name: 'Salt and vinegar crisps', portion: '1 bag', protein_g: 2, calories_g: 150, estimated_grams: 30 },
  { name: 'Ready salted crisps', portion: '1 bag', protein_g: 2, calories_g: 150, estimated_grams: 30 },
  { name: 'Prawn cocktail crisps', portion: '1 bag', protein_g: 2, calories_g: 150, estimated_grams: 30 },
  { name: 'Walkers crisps', portion: '1 bag', protein_g: 2, calories_g: 150, estimated_grams: 30 },
  { name: 'Quavers', portion: '1 bag', protein_g: 1, calories_g: 110, estimated_grams: 16 },
  { name: 'Wotsits', portion: '1 bag', protein_g: 1.5, calories_g: 120, estimated_grams: 16 },
  { name: 'Monster Munch', portion: '1 bag', protein_g: 1.5, calories_g: 130, estimated_grams: 22 },
  { name: 'Hula Hoops', portion: '1 bag', protein_g: 1.5, calories_g: 130, estimated_grams: 24 },
  { name: 'Pom Bears', portion: '1 bag', protein_g: 1, calories_g: 100, estimated_grams: 15 },
  { name: 'Mini Cheddars', portion: '1 bag', protein_g: 3, calories_g: 140, estimated_grams: 25 },
  { name: 'Cheese string', portion: '1 stick', protein_g: 5, calories_g: 70, estimated_grams: 20, aliases: ['string cheese uk'] },
  { name: 'Babybel', portion: '1 cheese', protein_g: 5, calories_g: 70, estimated_grams: 20 },
  { name: 'Laughing Cow', portion: '1 triangle', protein_g: 2, calories_g: 35, estimated_grams: 15 },
  { name: 'Philadelphia cheese', portion: '2 tbsp', protein_g: 2, calories_g: 80, estimated_grams: 30, aliases: ['philly cheese', 'philadelphia'] },
  { name: 'Dairylea', portion: '1 triangle', protein_g: 2, calories_g: 40, estimated_grams: 15 },
  { name: 'Cathedral City cheddar', portion: '1 slice', protein_g: 7, calories_g: 110, estimated_grams: 28 },
  { name: 'Heinz tomato soup', portion: '1 bowl', protein_g: 2, calories_g: 120, estimated_grams: 250 },
  { name: 'Heinz spaghetti', portion: '0.5 can', protein_g: 4, calories_g: 140, estimated_grams: 200 },
  { name: 'Heinz ravioli', portion: '0.5 can', protein_g: 6, calories_g: 160, estimated_grams: 200 },
  { name: 'Pot Noodle', portion: '1 pot', protein_g: 8, calories_g: 400, estimated_grams: 90, aliases: ['pot noodle'] },
  { name: 'Super Noodles', portion: '1 pack', protein_g: 6, calories_g: 350, estimated_grams: 85 },
  { name: 'Cup a Soup', portion: '1 cup', protein_g: 1, calories_g: 70, estimated_grams: 200 },
  { name: 'Marmite', portion: '1 tsp', protein_g: 1.5, calories_g: 10, estimated_grams: 5 },
  { name: 'Vegemite', portion: '1 tsp', protein_g: 1.5, calories_g: 10, estimated_grams: 5 },
  { name: 'Bovril', portion: '1 tsp', protein_g: 1, calories_g: 10, estimated_grams: 5 },
  { name: 'HP Sauce', portion: '1 tbsp', protein_g: 0.3, calories_g: 20, estimated_grams: 15, aliases: ['brown sauce', 'hp brown sauce'] },
  { name: 'Salad cream', portion: '1 tbsp', protein_g: 0.2, calories_g: 40, estimated_grams: 15 },
  { name: 'Branston pickle', portion: '1 tbsp', protein_g: 0.2, calories_g: 25, estimated_grams: 20, aliases: ['branston', 'pickle relish'] },
  { name: 'Colman\'s mustard', portion: '1 tsp', protein_g: 0.3, calories_g: 10, estimated_grams: 5 },
  { name: 'English mustard', portion: '1 tsp', protein_g: 0.3, calories_g: 8, estimated_grams: 5 },
  { name: 'Piccalilli', portion: '1 tbsp', protein_g: 0.2, calories_g: 20, estimated_grams: 20 },
  { name: 'Cranberry sauce', portion: '1 tbsp', protein_g: 0, calories_g: 40, estimated_grams: 20 },
  { name: 'Apple sauce', portion: '2 tbsp', protein_g: 0.1, calories_g: 40, estimated_grams: 30, aliases: ['applesauce'] },
  { name: 'Custard (tinned)', portion: '0.5 cup', protein_g: 3, calories_g: 120, estimated_grams: 120 },
  { name: 'Rice pudding (tinned)', portion: '0.5 can', protein_g: 5, calories_g: 180, estimated_grams: 150 },
  { name: 'Ambrosia custard', portion: '0.5 cup', protein_g: 3, calories_g: 130, estimated_grams: 120 },
  { name: 'Trifle', portion: '1 serving', protein_g: 4, calories_g: 280, estimated_grams: 150 },
  { name: 'Sticky toffee pudding', portion: '1 serving', protein_g: 4, calories_g: 400, estimated_grams: 150 },
  { name: 'Spotted dick', portion: '1 serving', protein_g: 4, calories_g: 320, estimated_grams: 140 },
  { name: 'Eton mess', portion: '1 serving', protein_g: 4, calories_g: 300, estimated_grams: 150 },
  { name: 'Victoria sponge', portion: '1 slice', protein_g: 3, calories_g: 280, estimated_grams: 80 },
  { name: 'Carrot cake', portion: '1 slice', protein_g: 3, calories_g: 320, estimated_grams: 90 },
  { name: 'Lemon drizzle cake', portion: '1 slice', protein_g: 3, calories_g: 280, estimated_grams: 80 },
  { name: 'Coffee cake', portion: '1 slice', protein_g: 3, calories_g: 300, estimated_grams: 80 },
  { name: 'Fruit cake', portion: '1 slice', protein_g: 3, calories_g: 280, estimated_grams: 80 },
  { name: 'Hot cross bun', portion: '1 bun', protein_g: 5, calories_g: 200, estimated_grams: 70 },
  { name: 'Teacake', portion: '1 teacake', protein_g: 4, calories_g: 180, estimated_grams: 60 },
  { name: 'Malted milk biscuit', portion: '1 biscuit', protein_g: 0.8, calories_g: 45, estimated_grams: 10 },
  { name: 'Rich Tea', portion: '1 biscuit', protein_g: 0.7, calories_g: 40, estimated_grams: 8 },
  { name: 'Hobnob', portion: '1 biscuit', protein_g: 1.2, calories_g: 70, estimated_grams: 15 },
  { name: 'Garibaldi biscuit', portion: '1 biscuit', protein_g: 0.8, calories_g: 50, estimated_grams: 10 },
  { name: 'Penguin biscuit', portion: '1 biscuit', protein_g: 1, calories_g: 80, estimated_grams: 18 },
  { name: 'Wagon Wheel', portion: '1 biscuit', protein_g: 1.5, calories_g: 140, estimated_grams: 35 },
  { name: 'Club biscuit', portion: '1 biscuit', protein_g: 1, calories_g: 100, estimated_grams: 22 },
  { name: 'Tunnocks teacake', portion: '1 teacake', protein_g: 1, calories_g: 100, estimated_grams: 25 },
  { name: 'Jammie Dodger', portion: '1 biscuit', protein_g: 0.8, calories_g: 80, estimated_grams: 18 },

  // —— Protein products ——
  {
    name: 'Whey protein isolate',
    portion: '1 scoop',
    protein_g: 25,
    calories_g: 110,
    estimated_grams: 30,
    aliases: ['whey isolate', 'isolate whey', 'wpi'],
  },
  {
    name: 'Whey protein concentrate',
    portion: '1 scoop',
    protein_g: 24,
    calories_g: 120,
    estimated_grams: 30,
    aliases: ['whey concentrate', 'wpc', 'whey protein'],
  },
  { name: 'Whey protein blend', portion: '1 scoop', protein_g: 24, calories_g: 115, estimated_grams: 30 },
  { name: 'Hydrolyzed whey', portion: '1 scoop', protein_g: 25, calories_g: 110, estimated_grams: 30, aliases: ['hydro whey'] },
  { name: 'Clear whey protein', portion: '1 scoop', protein_g: 20, calories_g: 90, estimated_grams: 25, aliases: ['clear whey', 'whey isolate clear'] },
  { name: 'Casein protein shake', portion: '1 scoop', protein_g: 24, calories_g: 120, estimated_grams: 30, aliases: ['night protein', 'slow release protein'] },
  { name: 'Egg white protein powder', portion: '1 scoop', protein_g: 24, calories_g: 110, estimated_grams: 30 },
  { name: 'Beef protein powder', portion: '1 scoop', protein_g: 24, calories_g: 120, estimated_grams: 30 },
  { name: 'Pea protein powder', portion: '1 scoop', protein_g: 20, calories_g: 110, estimated_grams: 30 },
  { name: 'Rice protein powder', portion: '1 scoop', protein_g: 20, calories_g: 110, estimated_grams: 30 },
  { name: 'Hemp protein powder', portion: '1 scoop', protein_g: 15, calories_g: 120, estimated_grams: 30 },
  { name: 'Soy protein powder', portion: '1 scoop', protein_g: 22, calories_g: 110, estimated_grams: 30, aliases: ['soya protein powder'] },
  { name: 'Collagen powder', portion: '1 scoop', protein_g: 18, calories_g: 70, estimated_grams: 20, aliases: ['collagen peptides'] },
  { name: 'Protein bar (chocolate)', portion: '1 bar', protein_g: 20, calories_g: 200, estimated_grams: 60, aliases: ['choc protein bar bar'] },
  { name: 'Protein bar (peanut butter)', portion: '1 bar', protein_g: 20, calories_g: 210, estimated_grams: 60 },
  { name: 'Protein bar (caramel)', portion: '1 bar', protein_g: 20, calories_g: 200, estimated_grams: 60 },
  { name: 'Protein bar (cookies and cream)', portion: '1 bar', protein_g: 20, calories_g: 200, estimated_grams: 60 },
  { name: 'Protein bar (birthday cake)', portion: '1 bar', protein_g: 20, calories_g: 200, estimated_grams: 60 },
  { name: 'Protein brownie', portion: '1 brownie', protein_g: 15, calories_g: 200, estimated_grams: 60 },
  { name: 'Protein cookie', portion: '1 cookie', protein_g: 15, calories_g: 200, estimated_grams: 60 },
  { name: 'Protein muffin', portion: '1 muffin', protein_g: 15, calories_g: 220, estimated_grams: 80 },
  { name: 'Protein pancakes', portion: '2 pancakes', protein_g: 25, calories_g: 300, estimated_grams: 150 },
  { name: 'Protein ice cream', portion: '1 serving', protein_g: 15, calories_g: 160, estimated_grams: 100 },
  { name: 'Protein cereal', portion: '1 bowl', protein_g: 15, calories_g: 180, estimated_grams: 40 },
  { name: 'Protein granola', portion: '0.5 cup', protein_g: 12, calories_g: 200, estimated_grams: 50 },
  { name: 'Protein milk', portion: '1 cup', protein_g: 15, calories_g: 120, estimated_grams: 250, aliases: ['high protein milk', 'fairlife style milk'] },
  { name: 'Protein pud', portion: '1 pot', protein_g: 20, calories_g: 150, estimated_grams: 180, aliases: ['protein pudding pot', 'high protein pudding'] },
  { name: 'RTD protein shake', portion: '1 bottle', protein_g: 25, calories_g: 160, estimated_grams: 330, aliases: ['ready to drink protein', 'protein carton'] },
  { name: 'Meal replacement bar', portion: '1 bar', protein_g: 15, calories_g: 220, estimated_grams: 60 },
  { name: 'SlimFast shake', portion: '1 shake', protein_g: 15, calories_g: 200, estimated_grams: 325 },
  { name: 'Huel', portion: '1 serving', protein_g: 20, calories_g: 400, estimated_grams: 90, aliases: ['huel powder'] },
  { name: 'Huel Ready-to-drink', portion: '1 bottle', protein_g: 20, calories_g: 400, estimated_grams: 500 },
  { name: 'Soylent', portion: '1 bottle', protein_g: 20, calories_g: 400, estimated_grams: 500 },
  { name: 'Creatine monohydrate', portion: '1 scoop', protein_g: 0, calories_g: 0, estimated_grams: 5, aliases: ['creatine mono'] },
  { name: 'Pre-workout', portion: '1 scoop', protein_g: 0, calories_g: 20, estimated_grams: 10, aliases: ['preworkout', 'pre workout'] },
  { name: 'Electrolyte drink', portion: '1 serving', protein_g: 0, calories_g: 20, estimated_grams: 500 },

  // —— Fruit / veg cooked vs raw ——
  { name: 'Apple (raw)', portion: '1 apple', protein_g: 0.5, calories_g: 95, estimated_grams: 182 },
  { name: 'Apple (baked)', portion: '1 apple', protein_g: 0.5, calories_g: 100, estimated_grams: 180 },
  { name: 'Banana (ripe)', portion: '1 banana', protein_g: 1.3, calories_g: 105, estimated_grams: 118 },
  { name: 'Banana (green)', portion: '1 banana', protein_g: 1.3, calories_g: 90, estimated_grams: 110 },
  { name: 'Banana chips', portion: '1 handful', protein_g: 1, calories_g: 150, estimated_grams: 30 },
  { name: 'Spinach (raw)', portion: '1 serving', protein_g: 2.9, calories_g: 23, estimated_grams: 100 },
  {
    name: 'Spinach (cooked)',
    portion: '1 serving',
    protein_g: 5,
    calories_g: 40,
    estimated_grams: 180,
    aliases: ['cooked spinach', 'wilted spinach'],
  },
  { name: 'Broccoli (raw)', portion: '1 serving', protein_g: 2.8, calories_g: 35, estimated_grams: 100 },
  { name: 'Broccoli (steamed)', portion: '1 serving', protein_g: 2.8, calories_g: 35, estimated_grams: 100, aliases: ['steamed broccoli'] },
  { name: 'Broccoli (roasted)', portion: '1 serving', protein_g: 3, calories_g: 60, estimated_grams: 100, aliases: ['roasted broccoli'] },
  { name: 'Carrot (raw)', portion: '1 carrot', protein_g: 0.6, calories_g: 25, estimated_grams: 60 },
  { name: 'Carrot (boiled)', portion: '1 serving', protein_g: 0.8, calories_g: 35, estimated_grams: 100 },
  { name: 'Carrot (roasted)', portion: '1 serving', protein_g: 0.8, calories_g: 50, estimated_grams: 100 },
  { name: 'Potato (boiled)', portion: '1 potato', protein_g: 3, calories_g: 130, estimated_grams: 150 },
  { name: 'Potato (baked)', portion: '1 potato', protein_g: 4, calories_g: 160, estimated_grams: 170 },
  { name: 'Potato (fried)', portion: '1 serving', protein_g: 3, calories_g: 300, estimated_grams: 100 },
  { name: 'Sweet potato (baked)', portion: '1 serving', protein_g: 2, calories_g: 110, estimated_grams: 130 },
  { name: 'Sweet potato (boiled)', portion: '1 serving', protein_g: 2, calories_g: 100, estimated_grams: 130 },
  { name: 'Sweet potato (mashed)', portion: '1 scoop', protein_g: 2, calories_g: 120, estimated_grams: 140 },
  { name: 'Corn on the cob', portion: '1 cob', protein_g: 3, calories_g: 90, estimated_grams: 90, aliases: ['corn cob', 'sweetcorn cob'] },
  { name: 'Sweetcorn (tinned)', portion: '0.5 cup', protein_g: 2.5, calories_g: 70, estimated_grams: 80, aliases: ['tinned sweetcorn', 'canned corn'] },
  { name: 'Sweetcorn (frozen)', portion: '0.5 cup', protein_g: 2.5, calories_g: 70, estimated_grams: 80 },
  { name: 'Peas (fresh)', portion: '0.5 cup', protein_g: 4, calories_g: 60, estimated_grams: 80 },
  { name: 'Peas (frozen)', portion: '0.5 cup', protein_g: 4, calories_g: 60, estimated_grams: 80 },
  { name: 'Mushrooms (raw)', portion: '1 serving', protein_g: 3, calories_g: 25, estimated_grams: 100 },
  { name: 'Mushrooms (fried)', portion: '1 serving', protein_g: 3, calories_g: 80, estimated_grams: 100, aliases: ['fried mushrooms'] },
  { name: 'Mushrooms (grilled)', portion: '1 serving', protein_g: 3, calories_g: 40, estimated_grams: 100 },
  { name: 'Portobello mushroom', portion: '1 mushroom', protein_g: 3, calories_g: 35, estimated_grams: 85 },
  { name: 'Chestnut mushrooms', portion: '1 serving', protein_g: 3, calories_g: 25, estimated_grams: 100 },
  { name: 'Tomato (raw)', portion: '1 tomato', protein_g: 1, calories_g: 22, estimated_grams: 120 },
  { name: 'Tomato (roasted)', portion: '1 serving', protein_g: 1, calories_g: 40, estimated_grams: 100 },
  { name: 'Cherry tomatoes', portion: '10 tomatoes', protein_g: 1, calories_g: 30, estimated_grams: 100 },
  { name: 'Onion (raw)', portion: '1 onion', protein_g: 1.1, calories_g: 44, estimated_grams: 110 },
  { name: 'Onion (fried)', portion: '1 serving', protein_g: 1, calories_g: 80, estimated_grams: 80, aliases: ['fried onions'] },
  { name: 'Onion (caramelised)', portion: '2 tbsp', protein_g: 0.5, calories_g: 60, estimated_grams: 40, aliases: ['caramelized onion'] },
  { name: 'Garlic (raw)', portion: '1 clove', protein_g: 0.2, calories_g: 4, estimated_grams: 3 },
  { name: 'Garlic (roasted)', portion: '1 clove', protein_g: 0.2, calories_g: 10, estimated_grams: 5 },
  { name: 'Peppers (raw)', portion: '1 pepper', protein_g: 1, calories_g: 30, estimated_grams: 120 },
  { name: 'Peppers (roasted)', portion: '1 serving', protein_g: 1, calories_g: 50, estimated_grams: 100 },
  { name: 'Courgette (raw)', portion: '1 serving', protein_g: 1.2, calories_g: 20, estimated_grams: 100 },
  { name: 'Courgette (grilled)', portion: '1 serving', protein_g: 1.2, calories_g: 25, estimated_grams: 100 },
  { name: 'Aubergine (grilled)', portion: '1 serving', protein_g: 1, calories_g: 40, estimated_grams: 100 },
  { name: 'Aubergine (fried)', portion: '1 serving', protein_g: 1, calories_g: 120, estimated_grams: 100 },
  { name: 'Cauliflower rice', portion: '1 cup', protein_g: 2, calories_g: 25, estimated_grams: 100 },
  { name: 'Cauliflower cheese', portion: '1 serving', protein_g: 10, calories_g: 250, estimated_grams: 200 },
  { name: 'Cauliflower steak', portion: '1 steak', protein_g: 3, calories_g: 80, estimated_grams: 150 },
  { name: 'Kale (raw)', portion: '1 serving', protein_g: 2.9, calories_g: 35, estimated_grams: 70 },
  { name: 'Kale (cooked)', portion: '1 serving', protein_g: 3.5, calories_g: 45, estimated_grams: 100 },
  { name: 'Green beans (steamed)', portion: '1 serving', protein_g: 2, calories_g: 35, estimated_grams: 100 },
  { name: 'Asparagus (steamed)', portion: '1 serving', protein_g: 2.5, calories_g: 25, estimated_grams: 100 },
  { name: 'Asparagus (grilled)', portion: '1 serving', protein_g: 2.5, calories_g: 30, estimated_grams: 100 },
  { name: 'Beetroot (cooked)', portion: '1 beet', protein_g: 1.5, calories_g: 40, estimated_grams: 80 },
  { name: 'Beetroot (pickled)', portion: '2 slices', protein_g: 0.5, calories_g: 20, estimated_grams: 40 },
  { name: 'Cabbage (raw)', portion: '1 serving', protein_g: 1.3, calories_g: 25, estimated_grams: 100 },
  { name: 'Cabbage (cooked)', portion: '1 serving', protein_g: 1.5, calories_g: 30, estimated_grams: 100 },
  { name: 'Red cabbage', portion: '1 serving', protein_g: 1.3, calories_g: 30, estimated_grams: 100 },
  { name: 'Savoy cabbage', portion: '1 serving', protein_g: 2, calories_g: 30, estimated_grams: 100 },
  { name: 'Pak choi', portion: '1 serving', protein_g: 1.5, calories_g: 15, estimated_grams: 100, aliases: ['bok choy', 'pak choy'] },
  { name: 'Mangetout', portion: '1 serving', protein_g: 2.5, calories_g: 40, estimated_grams: 80, aliases: ['snow peas'] },
  { name: 'Sugar snap peas', portion: '1 serving', protein_g: 2.5, calories_g: 40, estimated_grams: 80 },
  { name: 'Artichoke', portion: '1 artichoke', protein_g: 3.5, calories_g: 60, estimated_grams: 120 },
  { name: 'Artichoke hearts', portion: '0.5 cup', protein_g: 2, calories_g: 40, estimated_grams: 80 },
  { name: 'Fennel', portion: '1 serving', protein_g: 1, calories_g: 30, estimated_grams: 100 },
  { name: 'Swede', portion: '1 serving', protein_g: 1, calories_g: 40, estimated_grams: 100, aliases: ['rutabaga'] },
  { name: 'Turnip', portion: '1 serving', protein_g: 1, calories_g: 30, estimated_grams: 100 },
  { name: 'Parsnip', portion: '1 serving', protein_g: 1.5, calories_g: 75, estimated_grams: 100 },
  { name: 'Parsnip (roasted)', portion: '1 serving', protein_g: 1.5, calories_g: 100, estimated_grams: 100 },
  { name: 'Celeriac', portion: '1 serving', protein_g: 1.5, calories_g: 40, estimated_grams: 100 },
  { name: 'Watercress', portion: '1 handful', protein_g: 1, calories_g: 10, estimated_grams: 30 },
  { name: 'Rocket', portion: '1 handful', protein_g: 0.8, calories_g: 10, estimated_grams: 20, aliases: ['arugula'] },
  { name: 'Mixed salad leaves', portion: '1 serving', protein_g: 1, calories_g: 15, estimated_grams: 50 },
  { name: 'Iceberg lettuce', portion: '1 serving', protein_g: 0.7, calories_g: 10, estimated_grams: 80 },
  { name: 'Romaine lettuce', portion: '1 serving', protein_g: 1, calories_g: 15, estimated_grams: 80, aliases: ['cos lettuce'] },
  { name: 'Avocado (half)', portion: '0.5 avocado', protein_g: 1.5, calories_g: 120, estimated_grams: 75 },
  { name: 'Guacamole', portion: '2 tbsp', protein_g: 1, calories_g: 50, estimated_grams: 30 },
  { name: 'Mango (ripe)', portion: '1 mango', protein_g: 1.4, calories_g: 150, estimated_grams: 200 },
  { name: 'Mango chunks', portion: '1 cup', protein_g: 1, calories_g: 100, estimated_grams: 165 },
  { name: 'Pineapple (fresh)', portion: '1 serving', protein_g: 0.5, calories_g: 50, estimated_grams: 100 },
  { name: 'Pineapple (tinned)', portion: '1 serving', protein_g: 0.4, calories_g: 60, estimated_grams: 100 },
  { name: 'Peaches (tinned)', portion: '0.5 cup', protein_g: 0.5, calories_g: 70, estimated_grams: 120 },
  { name: 'Fruit cocktail (tinned)', portion: '0.5 cup', protein_g: 0.5, calories_g: 80, estimated_grams: 120 },
  { name: 'Dried apricots', portion: '5 apricots', protein_g: 1, calories_g: 80, estimated_grams: 35 },
  { name: 'Prunes', portion: '5 prunes', protein_g: 1, calories_g: 100, estimated_grams: 40 },
  { name: 'Dried figs', portion: '2 figs', protein_g: 1, calories_g: 80, estimated_grams: 40 },
  { name: 'Goji berries', portion: '1 handful', protein_g: 2, calories_g: 70, estimated_grams: 20 },
  { name: 'Acai puree', portion: '1 packet', protein_g: 1, calories_g: 70, estimated_grams: 100 },
  { name: 'Smoothie (banana berry)', portion: '1 glass', protein_g: 3, calories_g: 180, estimated_grams: 300 },
  { name: 'Smoothie (green)', portion: '1 glass', protein_g: 4, calories_g: 150, estimated_grams: 300 },
  { name: 'Smoothie (protein)', portion: '1 glass', protein_g: 25, calories_g: 250, estimated_grams: 350 },
  { name: 'Fresh orange juice', portion: '1 glass', protein_g: 1.5, calories_g: 110, estimated_grams: 240, aliases: ['oj', 'fresh oj'] },
  { name: 'Orange juice (from concentrate)', portion: '1 glass', protein_g: 1, calories_g: 110, estimated_grams: 240 },

  // —— Fast food / cafe basics ——
  { name: 'McDonald\'s Big Mac', portion: '1 burger', protein_g: 25, calories_g: 550, estimated_grams: 220, aliases: ['big mac'] },
  { name: 'McDonald\'s McChicken', portion: '1 burger', protein_g: 18, calories_g: 400, estimated_grams: 180, aliases: ['mcchicken'] },
  { name: 'McDonald\'s fries', portion: '1 medium', protein_g: 4, calories_g: 340, estimated_grams: 110, aliases: ['maccies fries', 'mcdonalds chips'] },
  { name: 'McDonald\'s McNuggets', portion: '6 nuggets', protein_g: 14, calories_g: 260, estimated_grams: 100, aliases: ['chicken mcnuggets', 'mcnuggets'] },
  { name: 'McDonald\'s Filet-O-Fish', portion: '1 burger', protein_g: 15, calories_g: 390, estimated_grams: 140, aliases: ['filet o fish', 'fillet o fish'] },
  { name: 'Burger King Whopper', portion: '1 burger', protein_g: 28, calories_g: 660, estimated_grams: 270, aliases: ['whopper'] },
  { name: 'KFC Original Recipe', portion: '1 piece', protein_g: 18, calories_g: 260, estimated_grams: 100, aliases: ['kfc chicken', 'kfc original'] },
  { name: 'KFC popcorn chicken', portion: '1 serving', protein_g: 16, calories_g: 280, estimated_grams: 100 },
  { name: 'KFC fries', portion: '1 regular', protein_g: 4, calories_g: 300, estimated_grams: 100 },
  { name: 'Nando\'s chicken breast', portion: '1 breast', protein_g: 40, calories_g: 250, estimated_grams: 180, aliases: ['nandos chicken', 'nandos breast'] },
  { name: 'Nando\'s chicken thigh', portion: '1 thigh', protein_g: 25, calories_g: 280, estimated_grams: 140, aliases: ['nandos thigh'] },
  { name: 'Nando\'s peri chips', portion: '1 regular', protein_g: 5, calories_g: 400, estimated_grams: 180, aliases: ['nandos chips'] },
  { name: 'Nando\'s spicy rice', portion: '1 regular', protein_g: 5, calories_g: 250, estimated_grams: 180 },
  { name: 'Subway turkey sub', portion: '6 inch', protein_g: 18, calories_g: 280, estimated_grams: 200 },
  { name: 'Subway chicken sub', portion: '6 inch', protein_g: 20, calories_g: 320, estimated_grams: 220 },
  { name: 'Subway tuna sub', portion: '6 inch', protein_g: 18, calories_g: 350, estimated_grams: 220 },
  { name: 'Subway meatball sub', portion: '6 inch', protein_g: 20, calories_g: 450, estimated_grams: 250 },
  { name: 'Dominos pizza slice', portion: '1 slice', protein_g: 12, calories_g: 280, estimated_grams: 100 },
  { name: 'Pizza Hut slice', portion: '1 slice', protein_g: 12, calories_g: 300, estimated_grams: 110 },
  { name: 'Papa John\'s slice', portion: '1 slice', protein_g: 12, calories_g: 290, estimated_grams: 100 },
  { name: 'Five Guys burger', portion: '1 burger', protein_g: 30, calories_g: 700, estimated_grams: 280 },
  { name: 'Five Guys fries', portion: '1 little', protein_g: 6, calories_g: 530, estimated_grams: 150 },
  { name: 'Chipotle chicken bowl', portion: '1 bowl', protein_g: 35, calories_g: 600, estimated_grams: 500 },
  { name: 'Chipotle burrito', portion: '1 burrito', protein_g: 30, calories_g: 700, estimated_grams: 450 },
  { name: 'Shake Shack burger', portion: '1 burger', protein_g: 25, calories_g: 500, estimated_grams: 200 },
  { name: 'Wagamama ramen', portion: '1 bowl', protein_g: 22, calories_g: 550, estimated_grams: 500 },
  { name: 'Wagamama katsu', portion: '1 plate', protein_g: 28, calories_g: 900, estimated_grams: 500 },
  { name: 'Itsu chicken gyoza', portion: '5 pieces', protein_g: 12, calories_g: 220, estimated_grams: 100 },
  { name: 'Itsu ramen', portion: '1 bowl', protein_g: 15, calories_g: 350, estimated_grams: 400 },
  { name: 'Leon chicken wrap', portion: '1 wrap', protein_g: 25, calories_g: 400, estimated_grams: 220 },
  { name: 'Pret chicken salad', portion: '1 pot', protein_g: 25, calories_g: 300, estimated_grams: 280 },
  { name: 'Pret avocado wrap', portion: '1 wrap', protein_g: 10, calories_g: 400, estimated_grams: 220 },
  { name: 'Starbucks latte', portion: '1 grande', protein_g: 12, calories_g: 190, estimated_grams: 350 },
  { name: 'Starbucks cappuccino', portion: '1 grande', protein_g: 10, calories_g: 140, estimated_grams: 350 },
  { name: 'Starbucks flat white', portion: '1 cup', protein_g: 9, calories_g: 170, estimated_grams: 300 },
  { name: 'Starbucks caramel frappuccino', portion: '1 grande', protein_g: 5, calories_g: 380, estimated_grams: 400 },
  { name: 'Costa latte', portion: '1 medium', protein_g: 10, calories_g: 180, estimated_grams: 350 },
  { name: 'Costa cappuccino', portion: '1 medium', protein_g: 9, calories_g: 150, estimated_grams: 320 },
  { name: 'Costa flat white', portion: '1 cup', protein_g: 8, calories_g: 160, estimated_grams: 280 },
  { name: 'Costa panini', portion: '1 panini', protein_g: 22, calories_g: 450, estimated_grams: 220 },
  { name: 'Greggs latte', portion: '1 regular', protein_g: 8, calories_g: 150, estimated_grams: 300 },
  { name: 'Greggs Yum Yum', portion: '1 pastry', protein_g: 4, calories_g: 300, estimated_grams: 80 },
  { name: 'Greggs doughnut', portion: '1 doughnut', protein_g: 3, calories_g: 250, estimated_grams: 70 },
  { name: 'Cafe latte oat milk', portion: '1 cup', protein_g: 3, calories_g: 140, estimated_grams: 300, aliases: ['oat latte', 'latte with oat milk'] },
  { name: 'Cafe latte soy milk', portion: '1 cup', protein_g: 7, calories_g: 130, estimated_grams: 300, aliases: ['soy latte', 'soya latte'] },
  { name: 'Cafe latte almond milk', portion: '1 cup', protein_g: 2, calories_g: 80, estimated_grams: 300, aliases: ['almond latte'] },
  { name: 'Iced matcha latte', portion: '1 cup', protein_g: 5, calories_g: 160, estimated_grams: 350 },
  { name: 'Protein latte', portion: '1 cup', protein_g: 20, calories_g: 180, estimated_grams: 350 },
  { name: 'Breakfast burrito', portion: '1 burrito', protein_g: 20, calories_g: 450, estimated_grams: 250 },
  { name: 'Breakfast muffin', portion: '1 muffin', protein_g: 15, calories_g: 350, estimated_grams: 150 },
  { name: 'Egg McMuffin', portion: '1 muffin', protein_g: 17, calories_g: 300, estimated_grams: 140, aliases: ['mcmuffin'] },
  { name: 'Sausage McMuffin', portion: '1 muffin', protein_g: 17, calories_g: 400, estimated_grams: 160 },
  { name: 'Hash brown', portion: '1 hash brown', protein_g: 1.5, calories_g: 140, estimated_grams: 50, aliases: ['hashbrown'] },
  { name: 'Pancakes with syrup', portion: '3 pancakes', protein_g: 8, calories_g: 450, estimated_grams: 200 },
  { name: 'Pancakes with bacon', portion: '1 serving', protein_g: 18, calories_g: 550, estimated_grams: 250 },
  { name: 'Waffle with syrup', portion: '1 waffle', protein_g: 5, calories_g: 320, estimated_grams: 100 },
  { name: 'Acai bowl with granola', portion: '1 bowl', protein_g: 6, calories_g: 350, estimated_grams: 350 },
  { name: 'Poke bowl (salmon)', portion: '1 bowl', protein_g: 30, calories_g: 480, estimated_grams: 400 },
  { name: 'Poke bowl (tuna)', portion: '1 bowl', protein_g: 32, calories_g: 450, estimated_grams: 400 },
  { name: 'Buddha bowl', portion: '1 bowl', protein_g: 15, calories_g: 450, estimated_grams: 400 },
  { name: 'Grain bowl', portion: '1 bowl', protein_g: 12, calories_g: 400, estimated_grams: 380 },
  { name: 'Chicken Caesar wrap', portion: '1 wrap', protein_g: 25, calories_g: 450, estimated_grams: 250 },
  { name: 'Falafel wrap', portion: '1 wrap', protein_g: 12, calories_g: 400, estimated_grams: 250 },
  { name: 'Halloumi wrap', portion: '1 wrap', protein_g: 18, calories_g: 450, estimated_grams: 250 },
  { name: 'Chicken burger (grilled)', portion: '1 burger', protein_g: 28, calories_g: 420, estimated_grams: 220 },
  { name: 'Chicken burger (fried)', portion: '1 burger', protein_g: 25, calories_g: 550, estimated_grams: 240 },
  { name: 'Veggie burger (bean)', portion: '1 burger', protein_g: 12, calories_g: 300, estimated_grams: 180 },
  { name: 'Fish burger', portion: '1 burger', protein_g: 18, calories_g: 400, estimated_grams: 180 },
  { name: 'Loaded fries', portion: '1 serving', protein_g: 12, calories_g: 550, estimated_grams: 250 },
  { name: 'Cheese fries', portion: '1 serving', protein_g: 10, calories_g: 500, estimated_grams: 220 },
  { name: 'Onion rings (fast food)', portion: '1 serving', protein_g: 4, calories_g: 320, estimated_grams: 100 },
  { name: 'Mozzarella sticks', portion: '4 sticks', protein_g: 12, calories_g: 320, estimated_grams: 100 },
  { name: 'Chicken wings (6)', portion: '6 wings', protein_g: 30, calories_g: 450, estimated_grams: 180 },
  { name: 'Boneless wings', portion: '6 pieces', protein_g: 24, calories_g: 400, estimated_grams: 150 },
  { name: 'Soft serve ice cream', portion: '1 cone', protein_g: 3, calories_g: 180, estimated_grams: 100 },
  { name: 'McFlurry', portion: '1 serving', protein_g: 5, calories_g: 340, estimated_grams: 150 },
  { name: 'Milkshake (cafe)', portion: '1 glass', protein_g: 9, calories_g: 400, estimated_grams: 350 },
  { name: 'Thick shake', portion: '1 glass', protein_g: 10, calories_g: 500, estimated_grams: 400 },
  { name: 'Smoothie bowl', portion: '1 bowl', protein_g: 5, calories_g: 300, estimated_grams: 350 },
  { name: 'Avo toast cafe', portion: '1 serving', protein_g: 8, calories_g: 320, estimated_grams: 180 },
  { name: 'Eggs Benedict', portion: '1 serving', protein_g: 20, calories_g: 450, estimated_grams: 220 },
  { name: 'Eggs Florentine', portion: '1 serving', protein_g: 18, calories_g: 400, estimated_grams: 220 },
  { name: 'Eggs Royale', portion: '1 serving', protein_g: 22, calories_g: 450, estimated_grams: 230 },
  { name: 'Shakshuka', portion: '1 serving', protein_g: 14, calories_g: 280, estimated_grams: 300 },
  { name: 'Huevos rancheros', portion: '1 serving', protein_g: 16, calories_g: 400, estimated_grams: 300 },
  { name: 'Breakfast taco', portion: '1 taco', protein_g: 10, calories_g: 200, estimated_grams: 100 },
  { name: 'Croissant (plain)', portion: '1 croissant', protein_g: 5, calories_g: 270, estimated_grams: 65 },
  { name: 'Croissant (almond)', portion: '1 croissant', protein_g: 6, calories_g: 350, estimated_grams: 80 },
  { name: 'Croissant (ham and cheese)', portion: '1 croissant', protein_g: 12, calories_g: 380, estimated_grams: 120 },
  { name: 'Pain au raisin', portion: '1 pastry', protein_g: 5, calories_g: 280, estimated_grams: 80 },
  { name: 'Cinnamon swirl', portion: '1 pastry', protein_g: 4, calories_g: 320, estimated_grams: 90 },
  { name: 'Banana bread slice', portion: '1 slice', protein_g: 3, calories_g: 220, estimated_grams: 70 },
  { name: 'Blueberry scone', portion: '1 scone', protein_g: 4, calories_g: 220, estimated_grams: 70 },
  { name: 'Cheese scone', portion: '1 scone', protein_g: 7, calories_g: 250, estimated_grams: 70 },
  { name: 'Fruit scone', portion: '1 scone', protein_g: 4, calories_g: 210, estimated_grams: 65 },
  { name: 'Cream tea', portion: '1 serving', protein_g: 8, calories_g: 450, estimated_grams: 200 },
  { name: 'Afternoon tea', portion: '1 serving', protein_g: 20, calories_g: 800, estimated_grams: 400 },

  // —— Oils / condiments extras ——
  { name: 'Extra virgin olive oil', portion: '1 tbsp', protein_g: 0, calories_g: 120, estimated_grams: 14, aliases: ['evoo', 'ev olive oil'] },
  { name: 'Light olive oil', portion: '1 tbsp', protein_g: 0, calories_g: 120, estimated_grams: 14 },
  { name: 'Vegetable oil spray', portion: '1 spray', protein_g: 0, calories_g: 5, estimated_grams: 1, aliases: ['frylight', 'cooking spray'] },
  { name: 'Groundnut oil', portion: '1 tbsp', protein_g: 0, calories_g: 120, estimated_grams: 14, aliases: ['peanut oil'] },
  { name: 'Mustard oil', portion: '1 tbsp', protein_g: 0, calories_g: 120, estimated_grams: 14 },
  { name: 'Ghee (clarified butter)', portion: '1 tbsp', protein_g: 0, calories_g: 120, estimated_grams: 13 },
  { name: 'Duck fat', portion: '1 tbsp', protein_g: 0, calories_g: 115, estimated_grams: 13 },
  { name: 'Lard', portion: '1 tbsp', protein_g: 0, calories_g: 115, estimated_grams: 13 },
  { name: 'Mayonnaise (light)', portion: '1 tbsp', protein_g: 0.1, calories_g: 35, estimated_grams: 15, aliases: ['light mayo', 'low fat mayo'] },
  { name: 'Mayonnaise (vegan)', portion: '1 tbsp', protein_g: 0.1, calories_g: 90, estimated_grams: 15, aliases: ['vegan mayo'] },
  { name: 'Garlic mayo', portion: '1 tbsp', protein_g: 0.2, calories_g: 95, estimated_grams: 15, aliases: ['garlic mayonnaise', 'aioli'] },
  { name: 'Chipotle mayo', portion: '1 tbsp', protein_g: 0.2, calories_g: 90, estimated_grams: 15 },
  { name: 'Ketchup (low sugar)', portion: '1 tbsp', protein_g: 0.2, calories_g: 10, estimated_grams: 17 },
  { name: 'Tomato ketchup', portion: '1 tbsp', protein_g: 0.2, calories_g: 20, estimated_grams: 17, aliases: ['tomato sauce ketchup'] },
  { name: 'Sweet chilli dipping sauce', portion: '1 tbsp', protein_g: 0.1, calories_g: 40, estimated_grams: 15 },
  { name: 'Soy sauce (light)', portion: '1 tbsp', protein_g: 1, calories_g: 8, estimated_grams: 16, aliases: ['light soy'] },
  { name: 'Soy sauce (dark)', portion: '1 tbsp', protein_g: 1, calories_g: 12, estimated_grams: 16, aliases: ['dark soy'] },
  { name: 'Tamari', portion: '1 tbsp', protein_g: 1.5, calories_g: 10, estimated_grams: 16 },
  { name: 'Mirin', portion: '1 tbsp', protein_g: 0, calories_g: 35, estimated_grams: 15 },
  { name: 'Rice vinegar', portion: '1 tbsp', protein_g: 0, calories_g: 3, estimated_grams: 15 },
  { name: 'Chilli oil', portion: '1 tsp', protein_g: 0, calories_g: 40, estimated_grams: 5, aliases: ['chili oil'] },
  { name: 'Chilli flakes', portion: '1 tsp', protein_g: 0.3, calories_g: 6, estimated_grams: 2, aliases: ['red pepper flakes'] },
  { name: 'Garam masala', portion: '1 tsp', protein_g: 0.3, calories_g: 6, estimated_grams: 2 },
  { name: 'Curry powder', portion: '1 tsp', protein_g: 0.3, calories_g: 6, estimated_grams: 2 },
  { name: 'Tikka masala paste', portion: '1 tbsp', protein_g: 1, calories_g: 40, estimated_grams: 15 },
  { name: 'Korma paste', portion: '1 tbsp', protein_g: 1, calories_g: 50, estimated_grams: 15 },
  { name: 'Thai green curry paste', portion: '1 tbsp', protein_g: 1, calories_g: 30, estimated_grams: 15 },
  { name: 'Thai red curry paste', portion: '1 tbsp', protein_g: 1, calories_g: 30, estimated_grams: 15 },
  { name: 'Harissa', portion: '1 tsp', protein_g: 0.3, calories_g: 10, estimated_grams: 5 },
  { name: 'Hummus', portion: '2 tbsp', protein_g: 2.5, calories_g: 70, estimated_grams: 30 },
  { name: 'Hummus (reduced fat)', portion: '2 tbsp', protein_g: 2.5, calories_g: 50, estimated_grams: 30 },
  { name: 'Baba ganoush', portion: '2 tbsp', protein_g: 1, calories_g: 50, estimated_grams: 30 },
  { name: 'Guacamole (shop)', portion: '2 tbsp', protein_g: 1, calories_g: 50, estimated_grams: 30 },
  { name: 'Salsa', portion: '2 tbsp', protein_g: 0.5, calories_g: 15, estimated_grams: 30 },
  { name: 'Guindilla peppers', portion: '2 peppers', protein_g: 0.2, calories_g: 10, estimated_grams: 20 },
  { name: 'Pickled onions', portion: '2 onions', protein_g: 0.2, calories_g: 15, estimated_grams: 20 },
  { name: 'Gherkins', portion: '2 gherkins', protein_g: 0.2, calories_g: 10, estimated_grams: 30, aliases: ['pickled gherkins'] },
  { name: 'Capers', portion: '1 tbsp', protein_g: 0.2, calories_g: 5, estimated_grams: 8 },
  { name: 'Sunflower seeds (roasted)', portion: '1 handful', protein_g: 6, calories_g: 170, estimated_grams: 28 },
  { name: 'Pumpkin seeds (roasted)', portion: '1 handful', protein_g: 7, calories_g: 160, estimated_grams: 28 },
  { name: 'Mixed seeds', portion: '1 tbsp', protein_g: 3, calories_g: 60, estimated_grams: 12 },
  { name: 'Pine nuts', portion: '1 tbsp', protein_g: 2, calories_g: 70, estimated_grams: 10 },
  { name: 'Walnuts', portion: '1 handful', protein_g: 4, calories_g: 180, estimated_grams: 28 },
  { name: 'Almonds (raw)', portion: '1 handful', protein_g: 6, calories_g: 160, estimated_grams: 28 },
  { name: 'Almonds (roasted)', portion: '1 handful', protein_g: 6, calories_g: 170, estimated_grams: 28 },
  { name: 'Cashews (roasted)', portion: '1 handful', protein_g: 5, calories_g: 160, estimated_grams: 28 },
  { name: 'Peanuts (salted)', portion: '1 handful', protein_g: 7, calories_g: 170, estimated_grams: 28 },
  { name: 'Peanuts (dry roasted)', portion: '1 handful', protein_g: 7, calories_g: 170, estimated_grams: 28 },
  { name: 'Peanut butter (smooth)', portion: '1 tbsp', protein_g: 4, calories_g: 95, estimated_grams: 16, aliases: ['smooth peanut butter'] },
  { name: 'Peanut butter (crunchy)', portion: '1 tbsp', protein_g: 4, calories_g: 95, estimated_grams: 16, aliases: ['crunchy peanut butter'] },
  { name: 'Peanut butter (no added sugar)', portion: '1 tbsp', protein_g: 4.5, calories_g: 90, estimated_grams: 16 },
  { name: 'Honey (runny)', portion: '1 tbsp', protein_g: 0, calories_g: 64, estimated_grams: 21 },
  { name: 'Honey (set)', portion: '1 tbsp', protein_g: 0, calories_g: 64, estimated_grams: 21 },
  { name: 'Manuka honey', portion: '1 tbsp', protein_g: 0, calories_g: 64, estimated_grams: 21 },
  { name: 'Date syrup', portion: '1 tbsp', protein_g: 0.2, calories_g: 55, estimated_grams: 20 },
  { name: 'Coconut sugar', portion: '1 tsp', protein_g: 0, calories_g: 15, estimated_grams: 4 },
  { name: 'Stevia', portion: '1 serving', protein_g: 0, calories_g: 0, estimated_grams: 1 },
  { name: 'Sweetener (tablets)', portion: '1 tablet', protein_g: 0, calories_g: 0, estimated_grams: 0.1 },
  { name: 'Canderel', portion: '1 tsp', protein_g: 0, calories_g: 2, estimated_grams: 1 },
  { name: 'Splenda', portion: '1 tsp', protein_g: 0, calories_g: 2, estimated_grams: 1 },

  // —— Eggs / breakfast extras ——
  { name: 'Egg white omelette', portion: '1 omelette', protein_g: 18, calories_g: 90, estimated_grams: 150 },
  { name: 'Cheese omelette', portion: '1 omelette', protein_g: 18, calories_g: 300, estimated_grams: 160 },
  { name: 'Mushroom omelette', portion: '1 omelette', protein_g: 14, calories_g: 220, estimated_grams: 160 },
  { name: 'Spanish omelette', portion: '1 slice', protein_g: 8, calories_g: 180, estimated_grams: 100, aliases: ['tortilla espanola'] },
  { name: 'Scrambled eggs (with milk)', portion: '2 eggs', protein_g: 13, calories_g: 200, estimated_grams: 120 },
  { name: 'Scrambled eggs (with butter)', portion: '2 eggs', protein_g: 12, calories_g: 220, estimated_grams: 120 },
  { name: 'Soft boiled egg', portion: '1 egg', protein_g: 6.3, calories_g: 72, estimated_grams: 50 },
  { name: 'Hard boiled egg', portion: '1 egg', protein_g: 6.3, calories_g: 72, estimated_grams: 50, aliases: ['hard-boiled egg', 'boiled egg'] },
  { name: 'Egg mayonnaise', portion: '2 tbsp', protein_g: 4, calories_g: 120, estimated_grams: 40, aliases: ['egg mayo'] },
  { name: 'Scotch pancake', portion: '1 pancake', protein_g: 2, calories_g: 70, estimated_grams: 30, aliases: ['drop scone'] },
  { name: 'Potato waffle', portion: '1 waffle', protein_g: 2, calories_g: 100, estimated_grams: 40, aliases: ['birdseye waffle'] },
  { name: 'Potato croquette', portion: '1 croquette', protein_g: 2, calories_g: 80, estimated_grams: 35 },
  { name: 'Hash browns (homemade)', portion: '1 serving', protein_g: 3, calories_g: 200, estimated_grams: 100 },
];
