// Generate ProteinQuest app icons from SVG template via Playwright.
import { chromium } from 'playwright';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { execSync } from 'node:child_process';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, '..');
const assetsDir = path.join(root, 'assets', 'images');
const publicDir = path.join(root, 'public');
const template = path.join(__dirname, 'icon-template.html');

const SIZES = {
  icon: 1024,
  foreground: 1024,
  splash: 1024,
  favicon: 48,
  favicon32: 32,
  appleTouch: 180,
};

function resizePng(input, output, size) {
  try {
    execSync(`sips -z ${size} ${size} "${input}" --out "${output}"`, { stdio: 'pipe' });
  } catch {
    execSync(
      `npx --yes sharp-cli -i "${input}" -o "${output}" resize ${size} ${size}`,
      { stdio: 'inherit', cwd: root },
    );
  }
}

async function renderVariant(browser, variant, size) {
  const page = await browser.newPage({
    viewport: { width: size, height: size },
    deviceScaleFactor: 1,
  });
  const url = `file://${template}?variant=${variant}`;
  await page.goto(url, { waitUntil: 'networkidle' });
  await page.setViewportSize({ width: size, height: size });
  const buffer = await page.screenshot({
    type: 'png',
    omitBackground: variant === 'foreground',
    clip: { x: 0, y: 0, width: size, height: size },
  });
  await page.close();
  return buffer;
}

async function main() {
  fs.mkdirSync(assetsDir, { recursive: true });
  const browser = await chromium.launch();

  const icon = await renderVariant(browser, 'full', SIZES.icon);
  fs.writeFileSync(path.join(assetsDir, 'icon.png'), icon);

  const foreground = await renderVariant(browser, 'foreground', SIZES.foreground);
  fs.writeFileSync(path.join(assetsDir, 'android-icon-foreground.png'), foreground);

  const splash = await renderVariant(browser, 'splash', SIZES.splash);
  fs.writeFileSync(path.join(assetsDir, 'splash-icon.png'), splash);

  // Web + app favicons from full icon
  const faviconTmp = path.join(assetsDir, '.favicon-tmp.png');
  fs.writeFileSync(faviconTmp, icon);
  fs.mkdirSync(publicDir, { recursive: true });

  const faviconOut = path.join(assetsDir, 'favicon.png');
  resizePng(faviconTmp, faviconOut, SIZES.favicon);

  const publicFavicon48 = path.join(publicDir, 'favicon-48.png');
  const publicFavicon32 = path.join(publicDir, 'favicon-32.png');
  const publicAppleTouch = path.join(publicDir, 'apple-touch-icon.png');
  resizePng(faviconTmp, publicFavicon48, SIZES.favicon);
  resizePng(faviconTmp, publicFavicon32, SIZES.favicon32);
  resizePng(faviconTmp, publicAppleTouch, SIZES.appleTouch);

  // favicon.ico is generated by `expo export` from app.json web.favicon (16/32/48 multi-size).
  fs.unlinkSync(faviconTmp);

  await browser.close();
  console.log('Generated icons in', assetsDir);
  for (const f of ['icon.png', 'android-icon-foreground.png', 'splash-icon.png', 'favicon.png']) {
    const stat = fs.statSync(path.join(assetsDir, f));
    console.log(`  ${f}: ${stat.size} bytes`);
  }
  console.log('Generated web icons in', publicDir);
  for (const f of ['favicon-32.png', 'favicon-48.png', 'apple-touch-icon.png']) {
    const stat = fs.statSync(path.join(publicDir, f));
    console.log(`  ${f}: ${stat.size} bytes`);
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
